(() => {
'use strict';
const VERSION='9.6.1';

function forceVersion(){
  const title=`チャス競馬研究所 Ver.${VERSION}`;
  if(document.title!==title) document.title=title;
  document.querySelectorAll('.topbar h1 span,h1 span').forEach(el=>{
    const next=`Ver.${VERSION}`;
    if(/Ver\./.test(el.textContent||'') && el.textContent!==next) el.textContent=next;
  });
}
function fmt(v,n=1){const x=Number(v);return Number.isFinite(x)?x.toFixed(n):'—';}
function abilityPlace(win, allWins){
  const w=Math.pow(Math.max(Number(win)||0.01,.01),.72);
  const den=allWins.reduce((s,x)=>s+Math.pow(Math.max(Number(x)||0.01,.01),.72),0)||1;
  return Math.max(1,Math.min(88,300*w/den));
}
function buildRoot(d,date,track,raceNo){
  const horses=Array.isArray(d.horses)?d.horses:[];
  const ready=horses.filter(h=>Number.isFinite(Number(h.abilityWinRate))).length;
  const wins=horses.map(h=>Number(h.abilityWinRate)||0);
  const abilityMode=ready>=Math.max(2,Math.ceil(horses.length*.5));
  return {
    race:{
      category:'地方競馬',raceDate:date,track:d.track||track,raceNo,
      raceName:d.raceName||'',distance:d.distance||'',surface:d.surface||'ダート',
      weather:d.weather||'',trackCondition:d.trackCondition||'不明',
      chaos:d.chaos??50,pace:d.pace||'標準',bias:d.bias||'',
      oddsType:Array.isArray(d.odds)&&d.odds.length?'実オッズ':'オッズなし',
      autoGenerated:true,
      dataSource:'NAR公式 Ver.9.6',
      dataMode:abilityMode?'NAR自動・能力先行':'NAR自動・能力不足',
      autoModel:abilityMode?'NAR past-runs ability first + market second':'NAR past-runs insufficient; no market-as-ability fallback',
      predictedTimePolicy:'NAR公式の同距離実走TIMEがある馬のみ推定'
    },
    horses:horses.map(h=>({
      horseNo:h.horseNo,
      horseName:h.horseName||`馬番${h.horseNo}`,
      popularity:h.popularity??null,
      realOdds:h.odds??null,
      runningStyle:h.runningStyle||'不明',
      weight:h.weight??null,
      jockey:h.jockey||'',trainer:h.trainer||'',sexAge:h.sexAge||'',
      timeIndex:h.timeIndex??null,
      fiveRaceAvgIndex:h.fiveRaceAvgIndex??null,
      distanceIndex:h.distanceIndex??null,
      courseIndex:h.courseIndex??null,
      recentIndex:Array.isArray(h.recentIndex)?h.recentIndex:[],
      predictedTime:h.predictedTime||'',
      aiWinRate:abilityMode?(h.abilityWinRate??null):null,
      aiPlaceRate:abilityMode&&Number.isFinite(Number(h.abilityWinRate))?abilityPlace(h.abilityWinRate,wins):null,
      dataMode:abilityMode?'NAR自動・能力先行':'NAR自動・能力不足',
      dataConfidence:h.dataConfidence??null,
      reason:h.reason||(abilityMode?'NAR公式過去走を能力側へ反映。実オッズは期待値判定のみで使用。':'解析可能な過去走が不足。市場を能力の代用には使用しません。')
    }))
  };
}
async function importRoot(root){
  const input=document.getElementById('raceImportFile');
  if(!input)throw new Error('予想データ入力欄を見つけられません');
  if(typeof DataTransfer!=='function')throw new Error('このブラウザでは自動取込に対応していません');
  const text=JSON.stringify(root);
  const file=new File([text],`chass-${VERSION}.json`,{type:'application/json'});
  const dt=new DataTransfer();dt.items.add(file);input.files=dt.files;
  input.dispatchEvent(new Event('change',{bubbles:true}));
  await new Promise(r=>setTimeout(r,250));
}
function addNote(){
 const d=document.getElementById('dashboardView');
 if(!d)return;
 document.getElementById('chass95note')?.remove();
 if(document.getElementById('chass96note'))return;
 const n=document.createElement('div');
 n.id='chass96note';n.className='card';
 n.innerHTML='<p class="eyebrow">CHASS 9.6 ABILITY-FIRST</p><h2>能力評価 → 市場評価を完全分離</h2><p class="muted">NAR公式の過去走表を実際の「競馬場MM.DD 馬場 距離」形式に合わせて再解析。同距離実時計・近走・距離/コース適性を先に評価し、単勝オッズはその後の期待値・💎穴馬・⚠️危険人気馬だけに使用します。能力データ不足時は市場を能力の代用品にしません。</p>';
 d.prepend(n);
}
function replaceAutoLoader(){
 const old=document.getElementById('autoRaceLoad');
 if(!old||old.dataset.chass96)return;
 const btn=old.cloneNode(true);btn.dataset.chass96='1';old.replaceWith(btn);
 btn.addEventListener('click',async()=>{
   const date=document.getElementById('autoRaceDate')?.value;
   const track=document.getElementById('autoTrack')?.value;
   const raceNo=Number(document.getElementById('autoRaceNo')?.value);
   const codes={'盛岡':10,'水沢':11,'浦和':18,'船橋':19,'大井':20,'川崎':21,'笠松':22,'金沢':23,'名古屋':24,'園田':27,'姫路':28,'高知':31,'佐賀':32,'門別':36};
   const code=codes[track];
   const badge=document.getElementById('autoRaceBadge'),status=document.getElementById('autoRaceStatus');
   if(!date||!code||!raceNo){if(status)status.textContent='日付・競馬場・レースを確認してください。';return;}
   try{
     if(badge)badge.textContent='能力取得中';
     if(status)status.textContent='NAR公式の過去走・同距離時計・距離/コース適性を解析しています…';
     const res=await fetch(`/api/nar/race?code=${code}&date=${encodeURIComponent(date)}&race=${raceNo}`,{cache:'no-store'});
     const d=await res.json();if(!res.ok)throw new Error(d.error||'取得失敗');
     if(!Array.isArray(d.horses)||d.horses.length<2)throw new Error('出走馬データを取得できませんでした');
     const root=buildRoot(d,date,track,raceNo);
     await importRoot(root);
     const ready=d.quality?.abilityData??d.horses.filter(h=>h.abilityScore!=null).length;
     const times=d.quality?.predictedTime??d.horses.filter(h=>h.predictedTime).length;
     if(badge)badge.textContent=`能力 ${ready}/${d.horses.length}`;
     if(status)status.textContent=`Ver.${VERSION}：NAR公式 ${d.horses.length}頭｜能力 ${ready}頭｜予想TIME ${times}頭｜市場と能力を分離して予想開始`;
     forceVersion();
   }catch(e){
     if(badge)badge.textContent='取得失敗';
     if(status)status.textContent='Ver.9.6 自動生成失敗：'+e.message;
   }
 });
}
function boot(){
 forceVersion();addNote();replaceAutoLoader();
 // app.js 9.4 の render() がヘッダーを戻すため、表示だけは常に9.6へ固定する。
 // iPhone/Safari hotfix: avoid a self-triggering MutationObserver loop.
 const header=document.querySelector('.topbar')||document.querySelector('header');
 if(header){
   const mo=new MutationObserver(()=>forceVersion());
   mo.observe(header,{subtree:true,childList:true,characterData:true});
 }
 setInterval(forceVersion,1500);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();