import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {parseJraResult,resolveJraResultUrl,extractJraPostTime,createJraResultService,JRA_RESULT_PARSER_VERSION} from './jra-result-fetch.mjs';import worker from './worker.js';
const card=fs.readFileSync(new URL('./jra-race-card-fixture.html',import.meta.url),'utf8'),html=fs.readFileSync(new URL('./jra-result-fixture.html',import.meta.url),'utf8');
const query={date:'2026-09-06',track:'中山',race:3},sample={date:'2026-09-05',track:'中山',race:5},token='pw01dde0106202604010520260905/16',listing=`<html><a href="/JRADB/accessD.html?CNAME=${token}">5R</a></html>`,sampleResult=html.replace('2026年9月6日','2026年9月5日').replace('4回中山2日','4回中山1日').replace('3レース','5レース');
const req=()=>new Request('https://app.test/api/jra/result?date=2026-09-05&track='+encodeURIComponent('中山')+'&race=5');
test('official semantic result table parses complete result and provenance',()=>{const d=parseJraResult(html,query);assert.equal(d.parserVersion,JRA_RESULT_PARSER_VERSION);assert.deepEqual(d.finishOrder,[4,11,9]);assert.equal(d.results.length,5);assert.equal(d.actualTimes['4'],'1:53.0');assert.deepEqual(d.results[0].cornerPositions,[13,11,3,2]);assert.equal(d.results[0].last3f,38.7);assert.equal(d.results[0].bodyWeightChange,-4);assert.equal(d.resultMeta.weather,'雨');assert.equal(d.resultMeta.trackCondition,'重');});
test('result link is accepted only when exact selected identity is present',()=>{assert.match(resolveJraResultUrl(card,sample),/^https:\/\/www\.jra\.go\.jp\/JRADB\/accessS/);for(const bad of [{...sample,date:'2026-09-06'},{...sample,track:'阪神'},{...sample,race:6}])assert.throws(()=>resolveJraResultUrl(card,bad),/JRA_RESULT_UNPUBLISHED/);assert.deepEqual(extractJraPostTime(card),{date:'2026-09-05',postTime:'12:30'});});
test('wrong identity, fewer than top3, duplicate horse and truncation fail closed',()=>{for(const broken of [html.replace('2026年9月6日','2026年9月7日'),html.replace(/<tr><td>3<\/td>[\s\S]*?<\/tr>/,'').replace(/<tr><td>4<\/td>[\s\S]*?<\/tr>/,'').replace(/<tr><td>5<\/td>[\s\S]*?<\/tr>/,''),html.replace('<td>11</td><td>ルシアージュ','<td>4</td><td>ルシアージュ'),html.replace('</html>','')])assert.throws(()=>parseJraResult(broken,query));});
test('feature flag off performs zero official requests',async()=>{let calls=0;const service=createJraResultService({fetchImpl:async()=>{calls++;return new Response('')}}),res=await service(req(),{});assert.equal(res.status,503);assert.equal((await res.json()).error,'JRA_RESULT_FETCH_DISABLED');assert.equal(calls,0);});
test('server blocks result-page request until five minutes after post',async()=>{let calls=0;const service=createJraResultService({now:()=>Date.parse('2026-09-05T12:33:00+09:00'),fetchImpl:async url=>{calls++;return new Response(url.includes('pw01dli00')?listing:card)}}),res=await service(req(),{ENABLE_JRA_RESULT_FETCH:true}),body=await res.json();assert.equal(res.status,409);assert.equal(body.error,'JRA_RESULT_BEFORE_POST');assert.equal(calls,2);});
test('result service resolves card then result, caches complete result',async()=>{let calls=0;const service=createJraResultService({now:()=>Date.parse('2026-09-06T12:00:00+09:00'),fetchImpl:async url=>{calls++;return new Response(url.includes('pw01dli00')?listing:url.includes('accessS')?sampleResult:card)}}),first=await service(req(),{ENABLE_JRA_RESULT_FETCH:'true'}),body=await first.json();assert.equal(first.status,200);assert.deepEqual(body.finishOrder,[4,11,9]);assert.equal(calls,3);const again=await service(req(),{ENABLE_JRA_RESULT_FETCH:true});assert.equal(again.headers.get('X-CHASS-JRA-Result-Cache'),'HIT');assert.equal(calls,3);});
test('unpublished and network errors remain distinct and do not retry',async()=>{let calls=0;const unpublished=createJraResultService({now:()=>Date.parse('2026-09-06T12:00:00+09:00'),fetchImpl:async url=>{calls++;return new Response(url.includes('pw01dli00')?listing:url.includes('accessS')?'<html><p>レース結果はまだ掲載しておりません</p></html>':card)}});assert.equal((await (await unpublished(req(),{ENABLE_JRA_RESULT_FETCH:true})).json()).error,'JRA_RESULT_UNPUBLISHED');assert.equal(calls,3);let failures=0;const offline=createJraResultService({fetchImpl:async()=>{failures++;throw Error('offline')}});assert.equal((await (await offline(req(),{ENABLE_JRA_RESULT_FETCH:true})).json()).error,'JRA_OFFICIAL_UNAVAILABLE');assert.equal(failures,1);});
test('Worker result endpoint validates input, method and feature flag',async()=>{assert.equal((await worker.fetch(new Request('https://app.test/api/jra/result?date=bad&track=x&race=99'),{})).status,400);assert.equal((await worker.fetch(req(),{})).status,503);assert.equal((await worker.fetch(new Request(req().url,{method:'POST'}),{ENABLE_JRA_RESULT_FETCH:true})).status,405);});
function client(fetchImpl){class E{constructor(){this.disabled=false;this.textContent='';}}const elements={narSync:new E(),narStatus:new E()};let active=true,generation=1,applied=0;const context={window:{},document:{getElementById:id=>elements[id]},fetch:fetchImpl,AbortController,URLSearchParams,setTimeout,clearTimeout};vm.runInNewContext(fs.readFileSync(new URL('./jra-result-client.js',import.meta.url),'utf8'),context);const api=context.window.CHASS_JRA_RESULT_CLIENT.create({isActive:()=>active,getSelection:()=>sample,getGeneration:()=>generation,apply:()=>applied++});api.setActive(true);return {api,elements,get applied(){return applied},stale(){generation++}};}
const payload={ok:true,finishOrder:[4,11,9],quality:{finishOrderCount:3,resultRows:5}};
test('result UI applies complete result and explains pending result',async()=>{const good=client(async()=>Response.json(payload));await good.api.load();assert.equal(good.applied,1);assert.match(good.elements.narStatus.textContent,/検証保存済み/);const pending=client(async()=>Response.json({ok:false,error:'JRA_RESULT_UNPUBLISHED'},{status:409}));await pending.api.load();assert.equal(pending.applied,0);assert.match(pending.elements.narStatus.textContent,/まだ掲載/);});
test('late result response cannot update a changed race',async()=>{let release;const c=client(()=>new Promise(r=>release=r));const p=c.api.load();c.stale();release(Response.json(payload));await p;assert.equal(c.applied,0);});
test('integration source freezes prediction and market before JRA result validation',()=>{const source=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');assert.match(source,/predictionBefore=snapshotFingerprint\(state\.predictionSnapshot\)/);assert.match(source,/marketBefore=snapshotFingerprint\(state\.marketSnapshot\)/);assert.match(source,/FROZEN_SNAPSHOT_MUTATED/);assert.match(source,/source:'JRA公式自動結果取得'/);});
test('saved JRA predictions enter the low-frequency result queue and reuse JRA calibration',()=>{const source=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');assert.match(source,/registerResultWaiting\(state,rid\)/);assert.match(source,/\/api\/jra\/result\?date=/);assert.match(source,/JRA公式 自動結果回収/);assert.match(source,/validationSnapshot\.jraCalibration=buildJraValidationMetrics\(next\)/);assert.match(source,/resultSource:identity\.organization==='JRA'\?'JRA_OFFICIAL'/);});
