import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {requestBridge} from '../mcp/bridge-client.mjs';
import {CONNECTOR_VERSION,createChassTools,jstDate,normalizeDate,normalizeTrack,prepareRace,TOOL_DEFINITIONS} from '../mcp/chass-tools.mjs';

const now=new Date('2026-08-31T15:30:00.000Z'); // 2026-09-01 00:30 JST
const race={
 raceId:'2026-09-01|大井|8',date:'2026-09-01',track:'大井',raceNo:8,distance:1600,surface:'ダート',class:'C2',postTime:'18:30',modelVersion:'9.9.30',status:'validated',predictionCreatedAt:'2026-09-01T08:00:00.000Z',oddsUpdatedAt:'2026-09-01T09:00:00.000Z',resultAcquiredAt:'2026-09-01T10:00:00.000Z',
 original:{volatility:{volatilityIndex:72,raceConfidence:54},horses:[
  {horseNo:1,horseName:'アルファ',mark:'◎',aiWinProbability:.22,aiPlaceProbability:.58,predictedTimeSeconds:98.4,predictedTimeDisplay:'1:38.4',expectedValue:118,popularity:2,odds:4.2,longshotMark:null,dangerMark:null,status:'active'},
  {horseNo:7,horseName:'ダイヤ',mark:'☆',aiWinProbability:.08,aiPlaceProbability:.35,predictedTimeSeconds:null,predictedTimeDisplay:null,predictedTimeMissingReason:'time_missing_no_history',expectedValue:146,popularity:8,odds:18.2,longshotMark:'💎💎💎',dangerMark:null,status:'active'},
  {horseNo:3,horseName:'注意馬',mark:'○',aiWinProbability:.16,aiPlaceProbability:.42,predictedTimeSeconds:99.1,predictedTimeDisplay:'1:39.1',expectedValue:88,popularity:1,odds:3.1,longshotMark:null,dangerMark:'⚠️',status:'active'}
 ]},
 liveAdjusted:{adjustedPredictionCreatedAt:'2026-09-01T09:10:00.000Z',volatility:{volatilityIndex:61,raceConfidence:63},horses:[{horseNo:1,horseName:'アルファ',mark:'◎',aiWinProbability:.31,aiPlaceProbability:.66,predictedTimeSeconds:98.4,status:'active'},{horseNo:7,horseName:'ダイヤ',mark:'○',aiWinProbability:.12,aiPlaceProbability:.42,predictedTimeSeconds:null,longshotMark:'💎💎💎',status:'active'}]},
 historicalSimilarity:{similarityVersion:'similarity_v1',original:{available:true,similarityVersion:'similarity_v1',mode:'shadow',adopted:false,similarRaceCount:42,similarityConfidence:82,confidenceLabel:'高',averageSimilarityScore:.81,metrics:{favoriteTop3Rate:{rate:.58,numerator:24,denominator:42},sevenPlusTop3Rate:{rate:.31,numerator:13,denominator:42},tenPlusTop3Rate:{rate:.12,numerator:5,denominator:42},favoriteCollapseRate:{rate:.37,numerator:16,denominator:42}},successPatterns:[{pattern:'high_place_low_market',label:'AI3着内率30%以上＋7人気以下',sampleCount:31,top3Rate:.39,lift:2.17}],failurePatterns:[{pattern:'top_ability_pace_mismatch',label:'能力1位＋上位人気＋展開不適合',sampleCount:22,failureRate:.55}],horseSupport:[{horseNo:7,classification:'support',historicalSimilaritySupport:78}],historicalConsensus:'high',historicalConflict:false,note:'Shadow補助'},liveAdjusted:null},
 scratch:{scratchCount:1,scratchDetectedAt:'2026-09-01T09:05:00.000Z',scratchHorses:[{horseNo:15,horseName:'取消馬',status:'scratched'}]},
 result:{finishOrder:[1,7,3],resultAcquiredAt:'2026-09-01T10:00:00.000Z',trackCondition:'良'},validation:{top3Captured:true,timeMae:0.4,longshotCaptured:true}
};

function fakeRequest(path,{query}={}){
 if(path.endsWith('/health'))return Promise.resolve({ok:true,bridgeVersion:'1.1',modelVersion:'9.9.34',database:true,generatedAt:'2026-09-01T10:01:00.000Z'});
 if(path.endsWith('/race'))return Promise.resolve({ok:true,race,generatedAt:'2026-09-01T10:01:00.000Z',query});
 if(path.endsWith('/research'))return Promise.resolve({ok:true,summary:{validatedRaces:194},researchMetrics:{validatedRaceCount:194,evaluatedHorseCount:2040,top3CaptureRate:84.3,timeMae:1.3,popular7PlusCaptured:{rate:25},popular10PlusCaptured:{rate:15.4}},longshotMetrics:{diamondTop3Rate:{rate:13.4}},volatilityMetrics:{highVolatilityActualUpsetRate:{rate:66}},similarityMetrics:{mode:'walk_forward_shadow',adopted:false,evaluatedCount:120},generatedAt:'2026-09-01T10:01:00.000Z'});
 if(path.endsWith('/pending'))return Promise.resolve({ok:true,pendingResults:{page:[{raceId:'2026-09-01|大井|9',status:'result_waiting'}],total:1,nextCursor:null},generatedAt:'2026-09-01T10:01:00.000Z'});
 if(query?.scope==='recent')return Promise.resolve({ok:true,recentRaces:{page:[race],total:1,nextCursor:null},generatedAt:'2026-09-01T10:01:00.000Z'});
 return Promise.resolve({ok:true,latestPredictions:{page:[race,{...race,raceId:'2026-09-01|船橋|8',track:'船橋'}],total:2,nextCursor:null},generatedAt:'2026-09-01T10:01:00.000Z'});
}

test('connector version and six focused tool definitions are stable',()=>{assert.equal(CONNECTOR_VERSION,'9.9.34');assert.deepEqual(Object.keys(TOOL_DEFINITIONS),['chass_health','chass_get_race','chass_get_latest','chass_get_pending','chass_get_research','chass_get_recent']);for(const tool of Object.values(TOOL_DEFINITIONS))assert.ok(tool.description.length>40)});
test('today is resolved in Asia/Tokyo and track aliases are explicit',()=>{assert.equal(jstDate(now),'2026-09-01');assert.equal(normalizeDate('today',now),'2026-09-01');assert.equal(normalizeDate('2026-02-30',now),null);assert.equal(normalizeTrack('Ohi'),'大井');assert.equal(normalizeTrack('おおい'),'大井');assert.equal(normalizeTrack('unknown'),null)});
test('race requires raceId or complete absolute race identity',async()=>{const tools=createChassTools({request:fakeRequest,now:()=>now}),bad=await tools.getRace({track:'大井',raceNo:8});assert.equal(bad.ok,false);assert.equal(bad.error,'invalid_request')});
test('race tool normalizes today and Ohi without guessing another field',async()=>{let captured;const tools=createChassTools({request:async(path,options)=>{captured={path,...options};return fakeRequest(path,options)},now:()=>now}),result=await tools.getRace({date:'today',track:'Ohi',raceNo:8,detail:'full'});assert.equal(result.ok,true);assert.deepEqual(captured.query,{date:'2026-09-01',track:'大井',raceNo:8,detail:'full'});assert.equal(result.data.race.original.predictionMode,'original');assert.equal(result.data.race.liveAdjusted.predictionMode,'live_adjusted');assert.equal(result.data.race.historicalSimilarity.original.similarRaceCount,42)});
test('compact race preserves volatility, Unicode marks, TIME null and Historical Similarity',()=>{const compact=prepareRace(race,{detail:'compact',now});assert.equal(compact.original.volatility.volatilityIndex,72);assert.equal(compact.original.longshots[0].longshotMark,'💎💎💎');assert.equal(compact.original.dangerFavorites[0].dangerMark,'⚠️');assert.equal(compact.original.longshots[0].predictedTimeSeconds,null);assert.equal(compact.historicalSimilarity.original.similarRaceCount,42);assert.equal(compact.historicalSimilarity.original.successPatterns[0].sampleCount,31);assert.equal(compact.provenance.source,'CHASS KEIBA LAB D1');assert.equal(compact.probabilityScale,'0-1')});
test('health reports read-only capabilities',async()=>{const out=await createChassTools({request:fakeRequest,now:()=>now}).health();assert.equal(out.data.connected,true);assert.equal(out.data.databaseAvailable,true);assert.equal(out.data.capabilities.historicalSimilarity,true);assert.equal(out.data.capabilities.readOnly,true)});
test('latest normalizes track and filters saved predictions',async()=>{const out=await createChassTools({request:fakeRequest,now:()=>now}).getLatest({track:'oi',limit:5});assert.equal(out.ok,true);assert.equal(out.data.races.length,1);assert.equal(out.data.races[0].race.track,'大井')});
test('pending, research and recent retain the Bridge facts',async()=>{const tools=createChassTools({request:fakeRequest,now:()=>now}),pending=await tools.getPending(),research=await tools.getResearch(),recent=await tools.getRecent({track:'大井',date:'today'});assert.equal(pending.data.pendingResults[0].status,'result_waiting');assert.equal(research.data.researchMetrics.validatedRaceCount,194);assert.equal(research.data.longshotMetrics.diamondTop3Rate.rate,13.4);assert.equal(research.data.similarityMetrics.mode,'walk_forward_shadow');assert.equal(recent.data.races[0].race.raceId,race.raceId)});
test('Bridge client sends token only in Authorization and encodes injection-like input',async()=>{let seen;const payload={ok:true,race},fetchImpl=async(url,options)=>{seen={url:String(url),options};return new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json'}})},attack="x' OR 1=1 --";await requestBridge('/api/chass/v1/race',{query:{raceId:attack},env:{CHASS_API_BASE_URL:'https://bridge.example',CHASS_BRIDGE_TOKEN:'top-secret',CHASS_HTTP_TIMEOUT_MS:'8000'},fetchImpl,retries:0});assert.equal(new URL(seen.url).searchParams.get('raceId'),attack);assert.equal(seen.url.includes('top-secret'),false);assert.equal(seen.options.headers.authorization,'Bearer top-secret')});
test('401, 429, 503 D1 and 413 map to stable connector errors',async()=>{for(const [status,payload,code] of [[401,{error:'unauthorized'},'unauthorized'],[429,{error:'rate_limit_exceeded'},'rate_limited'],[503,{error:'d1_read_failed'},'database_unavailable'],[413,{error:'response_too_large'},'response_too_large']]){await assert.rejects(()=>requestBridge('/api/chass/v1/context',{env:{CHASS_API_BASE_URL:'https://bridge.example',CHASS_BRIDGE_TOKEN:'x'},fetchImpl:async()=>new Response(JSON.stringify(payload),{status}),sleep:async()=>{},retries:0}),error=>error.code===code)}});
test('GET retries once after transport failure and then succeeds',async()=>{let calls=0;const body=await requestBridge('/api/chass/v1/health',{env:{CHASS_API_BASE_URL:'https://bridge.example',CHASS_BRIDGE_TOKEN:'x'},fetchImpl:async()=>{calls++;if(calls===1)throw new TypeError('fetch failed');return new Response('{"ok":true}',{status:200})},sleep:async()=>{},retries:1});assert.equal(body.ok,true);assert.equal(calls,2)});
test('AbortError is classified as timeout without exposing secrets',async()=>{await assert.rejects(()=>requestBridge('/api/chass/v1/health',{env:{CHASS_API_BASE_URL:'https://bridge.example',CHASS_BRIDGE_TOKEN:'never-print'},fetchImpl:async()=>{throw Object.assign(new Error('aborted'),{name:'AbortError'})},sleep:async()=>{},retries:0}),error=>error.code==='timeout'&&!error.message.includes('never-print'))});
test('connector source contains no NAR access or write tools and ignores env files',async()=>{const [client,tools,server,gitignore]=await Promise.all(['../mcp/bridge-client.mjs','../mcp/chass-tools.mjs','../mcp/server.mjs','../.gitignore'].map(file=>readFile(new URL(file,import.meta.url),'utf8')));const source=`${client}\n${tools}\n${server}`;assert.doesNotMatch(source,/keiba\.go\.jp|\/api\/nar\//);assert.doesNotMatch(source,/save_prediction|update_prediction|delete_race|trigger_sync|fetch_nar/);assert.match(gitignore,/^\.env$/m);assert.match(gitignore,/mcp\/\.env/);assert.doesNotMatch(source,/console\.(?:log|info)\([^\n]*(?:CHASS_BRIDGE_TOKEN|token)/i)});
test('MCP server declares every tool read-only and uses Streamable HTTP',async()=>{const source=await readFile(new URL('../mcp/server.mjs',import.meta.url),'utf8');assert.match(source,/StreamableHTTPServerTransport/);assert.match(source,/readOnlyHint:true/);assert.match(source,/destructiveHint:false/);assert.match(source,/openWorldHint:false/);assert.equal((source.match(/server\.registerTool\('/g)||[]).length,6)});
