import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import worker,{handlePublicApi,normalizePublicTrack} from '../worker.js';

test('light day keeps 12 races and 216 horses under 50KB without raw details',async()=>{
 const rows=Array.from({length:12},(_,i)=>{
  const r=row('大井','2026-09-01',i+1),p=JSON.parse(r.prediction_json);
  p.horses=Array.from({length:18},(_,j)=>({...p.horses[j%2],horseNo:j+1,horseName:'テストホース'+(j+1),rawHtml:'DO_NOT_EXPOSE'.repeat(1000)}));
  r.prediction_json=JSON.stringify(p);r.market_json=JSON.stringify({acquiredAt:'2026-09-01T09:05:00Z',horses:p.horses});return r;
 });
 const url='/api/chass/v1/public/day-ai?date=2026-09-01&track=大井&organization=NAR&format=tabular',db=new PublicD1(rows);
 const response=await handlePublicApi(request(url),{DB:db}),text=await response.text(),data=JSON.parse(text),bytes=Buffer.byteLength(text);
 assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/^application\/json/);
 assert.equal(data.raceCount,12);assert.equal(data.races.reduce((n,r)=>n+r.horses.length,0),216);
 assert.ok(bytes<50000);assert.equal(Number(response.headers.get('X-CHASS-Response-Bytes')),bytes);
 assert.ok(!text.includes('DO_NOT_EXPOSE'));
 const horseKeys=['horseNumber','horseName','abilityRank','score','winProb','top3Prob','odds','popularity','expectedValue','evRank','abilityPopularityGap','diamond','warning'];
 assert.deepEqual(data.horseColumns,horseKeys);assert.equal(data.schemaVersion,'day-ai-tabular-1');
 for(const r of data.races){assert.deepEqual(Object.keys(r),['raceNumber','raceName','raceVolatility','raceValueScore','favoriteReliability','horses']);for(const h of r.horses)assert.equal(h.length,horseKeys.length)}
 const old=await handlePublicApi(request(url.replace('format=tabular','format=full')),{DB:new PublicD1(rows)});
 assert.equal(old.status,413);
 const compactResponse=await handlePublicApi(request(url.replace('format=tabular','format=compact')),{DB:new PublicD1(rows)}),compactText=await compactResponse.text(),compact=JSON.parse(compactText);
 assert.equal(compactResponse.status,200);assert.equal(compact.raceCount,12);assert.equal(compact.evaluationMode,'ability-only');assert.equal(compact.races.reduce((n,r)=>n+r.horses.length,0),216);assert.ok(Buffer.byteLength(compactText)<100000);assert.ok(!compactText.includes('DO_NOT_EXPOSE'));for(const race of compact.races)for(const horse of race.horses)for(const key of ['odds','popularity','expectedValue','evRank','diamond','warning','longshot','danger'])assert.equal(key in horse,false,key);
 const detail=await handlePublicApi(request('/api/chass/v1/public/race-ai?date=2026-09-01&track=大井&organization=NAR&race=1'),{DB:new PublicD1(rows)});
 assert.equal(detail.status,200);assert.equal((await detail.json()).horses.length,18);assert.equal(db.writes,0);
 console.log('TABULAR_DAY_216_HORSES_BYTES='+bytes);console.log('COMPACT_DAY_216_HORSES_BYTES='+Buffer.byteLength(compactText));
});

test('compact market values equal rounded full values; detail alias and HEAD remain read-only',async()=>{
 const base='/api/chass/v1/public/day-ai?date=2026-09-01&track=大井&organization=NAR&format=compact';
 const fetch=async(path,method='GET')=>handlePublicApi(request(path,method),{DB:new PublicD1([row('大井','2026-09-01',1)])});
 const lightResponse=await fetch(base),light=await lightResponse.json();
 assert.equal(light.format,'compact');assert.ok(Number(lightResponse.headers.get('X-CHASS-Response-Bytes'))<100000);
 for(const h of light.races[0].horses){assert.ok(h.abilityRank>=1);assert.ok(h.win>=0);assert.ok(h.top3>=h.win);assert.equal(typeof h.time==='number'||h.time===null,true);assert.equal('expectedValue'in h,false);assert.equal('diamond'in h,false);assert.equal('warning'in h,false)}
 assert.equal(await (await fetch(base,'HEAD')).text(),'');
 const detail='/api/chass/v1/public/race-ai?date=2026-09-01&track=大井&organization=NAR&race=1';
 for(const method of ['POST','PUT','PATCH','DELETE'])assert.equal((await fetch(detail,method)).status,405);
 assert.equal((await fetch(detail.replace('race=1','race=12'))).status,404);
});

const prediction=(track,date,raceNo,{win=35,place=68,statusByHorse={}}={})=>({schemaVersion:3,modelVersion:'10.0.1',createdAt:`${date}T09:00:00.000Z`,race:{raceDate:date,track,raceNo,raceName:'テスト競走',surface:track==='新潟'?'芝':'ダート',distance:1600,trackCondition:'良',postTime:'15:40',fieldSize:2},horses:[{horseNo:1,frameNo:1,horseName:'アルファ',win,place,predictedTime:'1:35.0',abilityScore:88,overall:90,odds:2.5,popularity:1,valueMark:'💎',valueType:'能力穴',warningMark:'⚠️',status:statusByHorse[1]||'active'},{horseNo:2,frameNo:2,horseName:'ベータ',win:20,place:52,predictedTime:'',predictedTimeMissingReason:'time_missing',abilityScore:79,overall:82,odds:5.1,popularity:2}]});
function row(track,date,raceNo,options={}){const p=prediction(track,date,raceNo,options),isJra=track==='新潟',result=options.result===false?null:{fetchedAt:`${date}T16:00:00.000Z`,source:isJra?'manual':'NAR公式',finishOrder:[1,2],trackCondition:'稍重',weather:'雨',actualTimes:{1:'1:35.3'},horses:[{horseNo:1,position:1,time:'1:35.3',last3f:35.1,cornerPositions:'2-2',odds:2.4,popularity:1}]};return {race_id:`${date}|${track}|${raceNo}`,model_version:'10.0.1',race_json:JSON.stringify({...p.race,organization:isJra?'JRA':'NAR',oddsType:isJra?'入力オッズ':'実オッズ',scratchAudit:options.scratchAudit||null}),prediction_json:JSON.stringify(p),market_json:JSON.stringify({acquiredAt:`${date}T09:05:00.000Z`,horses:p.horses}),final_json:JSON.stringify({top3:p.horses.map((h,i)=>({horseNo:h.horseNo,mark:i?'○':'◎'}))}),result_json:result?JSON.stringify(result):null,validation_json:result?JSON.stringify({generatedAt:`${date}T16:01:00.000Z`,failures:[]}):null,prediction_created_at:p.createdAt,result_acquired_at:result?.fetchedAt||null,status:result?'validated':'result_waiting',updated_at:result?.fetchedAt||p.createdAt}}
class PublicD1{
 constructor(rows){this.rows=rows;this.sql=[];this.writes=0}
 prepare(sql){this.sql.push(String(sql));const db=this,args=[];return {bind(...values){args.splice(0,args.length,...values);return this},async first(){if(/^SELECT 1/i.test(sql.trim()))return {ok:1};return null},async all(){if(/FROM races/i.test(sql)){let rows=db.rows;if(/race_id LIKE \?/i.test(sql)){const prefix=String(args[0]||'').replace(/%$/,'');rows=rows.filter(r=>r.race_id.startsWith(prefix))}return {results:rows.slice(0,Number(args.at(-1))||rows.length)}}if(/FROM predictions/i.test(sql))return {results:db.rows.map(r=>({race_id:r.race_id,model_version:r.model_version,horse_count:2}))};if(/FROM results/i.test(sql))return {results:[]};return {results:[]}}}}
 async batch(statements=[]){if(statements.some(x=>x&&!x.__bridgeNoop))this.writes++;return []}
}
const request=(path,method='GET')=>new Request(`https://example.test${path}`,{method,headers:{'cf-connecting-ip':`${Math.random()}`}});
const body=async response=>({response,json:response.status===204||response.status===405&&response.body===null?null:await response.json()});

test('public track aliases cover NAR and JRA without guessing',()=>{assert.equal(normalizePublicTrack('TCK'),'大井');assert.equal(normalizePublicTrack('Niigata'),'新潟');assert.equal(normalizePublicTrack('unknown'),null)});
test('public health is unauthenticated read-only JSON',async()=>{const db=new PublicD1([]),response=await worker.fetch(request('/api/chass/v1/public/health'),{DB:db}),data=await response.json();assert.equal(response.status,200);assert.equal(data.mode,'read-only');assert.equal(data.apiVersion,'1');assert.equal(db.writes,0)});
test('race endpoint returns whitelisted JRA snapshot and preserves invalid probability',async()=>{const db=new PublicD1([row('新潟','2026-08-30',8,{win:58.3,place:39.5})]),response=await handlePublicApi(request('/api/chass/v1/public/race?date=2026-08-30&track=Niigata&race=8'),{DB:db}),data=await response.json();assert.equal(response.status,200);assert.equal(data.race.organization,'JRA');assert.equal(data.horses[0].probability.win,.583);assert.equal(data.horses[0].probability.top3,.395);assert.equal(data.validation.probabilityValid,false);assert.equal(db.writes,0)});
test('NAR race alias, Unicode marks, null TIME and excluded runner are preserved',async()=>{const db=new PublicD1([row('大井','2026-09-01',10,{scratchAudit:{statusByHorse:{1:'excluded'}}})]),data=await (await handlePublicApi(request('/api/chass/v1/public/race?date=2026-09-01&track=TCK&race=10'),{DB:db})).json();assert.equal(data.race.organization,'NAR');assert.equal(data.horses[0].longshot.mark,'💎');assert.equal(data.horses[0].danger.mark,'⚠️');assert.equal(data.horses[0].runnerStatus,'excluded');assert.equal(data.horses[1].predictedTime.standard,null)});
test('compact, latest, recent and races endpoints remain bounded',async()=>{const db=new PublicD1([row('大井','2026-09-01',10),row('新潟','2026-08-30',8)]),compact=await (await handlePublicApi(request('/api/chass/v1/public/race?date=2026-09-01&track=oi&race=10&format=compact'),{DB:db})).json(),latest=await (await handlePublicApi(request('/api/chass/v1/public/latest?organization=NAR'),{DB:db})).json(),recent=await (await handlePublicApi(request('/api/chass/v1/public/recent?limit=99'),{DB:db})).json(),races=await (await handlePublicApi(request('/api/chass/v1/public/races?date=2026-09-01&track=大井'),{DB:db})).json();assert.equal(compact.horses[0].no,1);assert.equal(compact.evaluationMode,'ability-only');assert.equal('odds'in compact.horses[0],false);assert.equal(latest.race.organization,'NAR');assert.ok(recent.count<=20);assert.equal(races.count,1)});
test('compact public reads query only the requested day and expose timing/cache diagnostics',async()=>{const rows=[row('大井','2026-09-01',10),...Array.from({length:200},(_,i)=>row('新潟','2026-08-30',i%12+1))],db=new PublicD1(rows),url='/api/chass/v1/public/race?date=2026-09-01&track=大井&race=10&organization=NAR&format=compact',first=await handlePublicApi(request(url),{DB:db}),a=await first.json(),second=await handlePublicApi(request(url),{DB:db}),b=await second.json();assert.equal(first.status,200);assert.equal(a.raceNumber,10);assert.equal(a.cacheHit,false);assert.equal(b.cacheHit,true);assert.ok(Number.isFinite(a.processingMs));assert.match(db.sql[0],/WHERE race_id LIKE \?/);assert.equal(db.sql.some(sql=>/FROM predictions|FROM results/.test(sql)),false);assert.equal(db.writes,0)});
test('ability compact is invariant to saved market values and contains no market timestamp',async()=>{const base=row('大井','2026-09-01',10),changed=JSON.parse(base.prediction_json);for(const h of changed.horses){h.odds=999;h.popularity=99;h.ev=999;h.valueMark='💎💎💎';h.warningMark='⚠️⚠️⚠️'}const altered={...base,prediction_json:JSON.stringify(changed),market_json:JSON.stringify({acquiredAt:'2099-01-01T00:00:00Z',horses:changed.horses})},url='/api/chass/v1/public/race?date=2026-09-01&track=大井&race=10&organization=NAR&format=compact',a=await (await handlePublicApi(request(url),{DB:new PublicD1([base])})).json(),b=await (await handlePublicApi(request(url),{DB:new PublicD1([altered])})).json();assert.deepEqual(a.horses,b.horses);for(const horse of a.horses)for(const key of ['odds','pop','ev','expectedValue','evRank','longshot','diamond','danger','warning','abilityPopularityGap','oddsStatus'])assert.equal(key in horse,false,key);assert.equal('timestamps'in a,false);assert.equal(a.horses[0].time,95)});
test('day endpoint returns every saved prediction for one track in race order',async()=>{const db=new PublicD1([row('大井','2026-09-01',10),row('大井','2026-09-01',1),row('新潟','2026-09-01',8)]),response=await handlePublicApi(request('/api/chass/v1/public/day?date=2026-09-01&track=TCK&organization=NAR'),{DB:db}),data=await response.json();assert.equal(response.status,200);assert.equal(data.organization,'NAR');assert.equal(data.count,2);assert.deepEqual(data.races.map(x=>x.race.raceNo),[1,10]);assert.equal(data.races[0].horses[0].no,1);assert.equal(data.races[0].horses[0].ability,undefined);assert.equal(db.writes,0)});
test('day endpoint uses multiline JSON so AI and text readers can expand the response',async()=>{const db=new PublicD1([row('大井','2026-09-01',1)]),response=await handlePublicApi(request('/api/chass/v1/public/day?date=2026-09-01&track=大井&organization=NAR&format=compact'),{DB:db}),text=await response.text();assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/^application\/json/);assert.ok(text.split('\n').length>10);assert.deepEqual(JSON.parse(text).races.map(x=>x.race.raceNo),[1])});
test('day-ai endpoint returns readable JSON with response-only market comparisons',async()=>{const db=new PublicD1([row('大井','2026-09-01',2),row('大井','2026-09-01',1)]),response=await handlePublicApi(request('/api/chass/v1/public/day-ai?date=2026-09-01&track=大井&organization=NAR&format=full'),{DB:db}),text=await response.text(),data=JSON.parse(text),race=data.races[0],horse=race.horses[0];assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/^application\/json/);assert.ok(text.split('\n').length>20);assert.equal(data.marketEvaluationMode,'saved-snapshot-only');assert.equal(data.meta.marketDataAvailable,true);assert.equal(data.meta.oddsCoverage,1);assert.equal(race.raceNumber,1);assert.equal(race.market.evRankStatus,'complete');assert.equal(race.market.oddsHorseCount,2);assert.equal(race.market.totalHorseCount,2);assert.equal(horse.abilityRank,1);assert.equal(horse.popularity,1);assert.equal(horse.expectedValue,.875);assert.equal(horse.expectedValuePercent,87.5);assert.equal(horse.evRank,2);assert.equal(horse.evRankStatus,'complete');assert.equal(horse.abilityPopularityGap,0);assert.equal(horse.diamond,'💎');assert.equal(horse.warning,'⚠️');assert.equal(race.abilityTop3[0].horseNumber,1);assert.equal(race.expectedValueTop3[0].horseNumber,2);assert.equal(db.writes,0)});
test('day-ai converts missing zero market values to null and never fabricates ranks or signals',async()=>{const missing=prediction('大井','2026-09-01',1);for(const horse of missing.horses){horse.odds=0;horse.popularity=0;horse.ev=0;delete horse.valueMark;delete horse.warningMark}const base=row('大井','2026-09-01',1),stored={...base,prediction_json:JSON.stringify(missing),market_json:JSON.stringify({acquiredAt:null,horses:missing.horses})},db=new PublicD1([stored]),data=await (await handlePublicApi(request('/api/chass/v1/public/day-ai?date=2026-09-01&track=大井&organization=NAR&format=full'),{DB:db})).json(),race=data.races[0];for(const horse of race.horses){assert.equal(horse.odds,null);assert.equal(horse.popularity,null);assert.equal(horse.expectedValue,null);assert.equal(horse.expectedValuePercent,null);assert.equal(horse.evRank,null);assert.equal(horse.diamond,null);assert.equal(horse.warning,null)}assert.deepEqual(race.expectedValueTop3,[]);assert.equal(race.raceValueScore,null);assert.equal(race.favoriteReliability,null);assert.equal(race.market.oddsStatus,'unavailable')});
test('day-ai labels partial odds and ranks only available differing values',async()=>{const partial=prediction('大井','2026-09-01',1);partial.horses[1].odds=0;partial.horses[1].popularity=0;const base=row('大井','2026-09-01',1),stored={...base,prediction_json:JSON.stringify(partial),market_json:JSON.stringify({acquiredAt:'2026-09-01T09:05:00.000Z',marketDataSource:'OddsTanFuku',horses:partial.horses})},db=new PublicD1([stored]),data=await (await handlePublicApi(request('/api/chass/v1/public/day-ai?date=2026-09-01&track=大井&organization=NAR&format=full'),{DB:db})).json(),race=data.races[0];assert.equal(race.market.oddsStatus,'partial');assert.equal(race.market.evRankStatus,'partial');assert.equal(race.market.oddsCoverage,.5);assert.equal(race.market.marketDataSource,'OddsTanFuku');assert.equal(race.horses[1].odds,null);assert.equal(race.horses[1].evRank,null)});
test('day-ai does not force EV ranks when every complete expected value is equal',async()=>{const tied=prediction('大井','2026-09-01',1);tied.horses[0].win=20;tied.horses[0].odds=5;tied.horses[1].win=25;tied.horses[1].odds=4;const base=row('大井','2026-09-01',1),stored={...base,prediction_json:JSON.stringify(tied),market_json:JSON.stringify({acquiredAt:'2026-09-01T09:05:00.000Z',horses:tied.horses})},db=new PublicD1([stored]),data=await (await handlePublicApi(request('/api/chass/v1/public/day-ai?date=2026-09-01&track=大井&organization=NAR&format=full'),{DB:db})).json();assert.deepEqual(data.races[0].horses.map(h=>h.evRank),[null,null])});
test('day-ai retains line-oriented compatibility with format=text',async()=>{const db=new PublicD1([row('大井','2026-09-01',1)]),response=await handlePublicApi(request('/api/chass/v1/public/day-ai?date=2026-09-01&track=大井&organization=NAR&format=text'),{DB:db}),text=await response.text();assert.match(response.headers.get('content-type'),/^text\/plain/);assert.match(text,/^CHASS_DAY_AI\|/);assert.match(text,/HORSE\|raceNo=1\|no=1\|name=アルファ\|abilityRank=1\|evRank=2/);assert.match(text,/diamond=💎\|warning=⚠️/);assert.match(text,/END_CHASS_DAY_AI$/)});
test('day endpoint requires date and track and returns 404 when no prediction is saved',async()=>{const db=new PublicD1([row('大井','2026-09-01',1)]);for(const [path,status,code] of [['/api/chass/v1/public/day?track=大井',400,'INVALID_PARAMETER'],['/api/chass/v1/public/day?date=2026-09-01',400,'INVALID_PARAMETER'],['/api/chass/v1/public/day?date=2026-09-02&track=大井',404,'RACE_NOT_FOUND']]){const response=await handlePublicApi(request(path),{DB:db}),data=await response.json();assert.equal(response.status,status);assert.equal(data.error.code,code)}});
test('result endpoint joins immutable original prediction and actual result',async()=>{const db=new PublicD1([row('大井','2026-09-01',10)]),data=await (await handlePublicApi(request('/api/chass/v1/public/result?date=2026-09-01&track=大井&race=10'),{DB:db})).json();assert.equal(data.result.horses[0].originalAiWinProb,.35);assert.equal(data.result.horses[0].timeErrorSec,.3);assert.equal(data.result.horses[0].actualTimeText,'1:35.3')});
test('missing parameters, unknown race and missing result use stable errors',async()=>{const db=new PublicD1([row('大井','2026-09-01',10,{result:false})]);for(const [path,status,code] of [['/api/chass/v1/public/race?track=大井&race=10',400,'INVALID_PARAMETER'],['/api/chass/v1/public/race?date=2026-09-01&race=10',400,'INVALID_PARAMETER'],['/api/chass/v1/public/race?date=2026-09-01&track=大井',400,'INVALID_PARAMETER'],['/api/chass/v1/public/race?date=2026-09-01&track=大井&race=9',404,'RACE_NOT_FOUND'],['/api/chass/v1/public/result?date=2026-09-01&track=大井&race=10',404,'RESULT_NOT_FOUND']]){const response=await handlePublicApi(request(path),{DB:db}),data=await response.json();assert.equal(response.status,status);assert.equal(data.error.code,code)}});
test('write methods are 405 while HEAD and OPTIONS expose no body',async()=>{const db=new PublicD1([]);for(const method of ['POST','PUT','PATCH','DELETE'])assert.equal((await handlePublicApi(request('/api/chass/v1/public/health',method),{DB:db})).status,405);const head=await handlePublicApi(request('/api/chass/v1/public/health','HEAD'),{DB:db}),options=await handlePublicApi(request('/api/chass/v1/public/health','OPTIONS'),{DB:db});assert.equal(head.status,200);assert.equal(await head.text(),'');assert.equal(options.status,204);assert.match(options.headers.get('access-control-allow-methods'),/HEAD/)});
test('public limiter is separated and returns 429 only after the normal allowance',async()=>{const db=new PublicD1([]),make=()=>new Request('https://example.test/api/chass/v1/public/health',{headers:{'cf-connecting-ip':'203.0.113.121'}});for(let i=0;i<120;i++)assert.equal((await handlePublicApi(make(),{DB:db})).status,200);const response=await handlePublicApi(make(),{DB:db});assert.equal(response.status,429);assert.equal((await response.json()).error.code,'RATE_LIMITED')});
test('public output contains no secret, authorization or SQL fields',async()=>{const db=new PublicD1([row('大井','2026-09-01',10)]),text=await (await handlePublicApi(request('/api/chass/v1/public/race?date=2026-09-01&track=大井&race=10'),{DB:db,CHASS_BRIDGE_TOKEN:'never-return',PRIVATE_KEY:'never-return'})).text();for(const term of ['never-return','AUTHORIZATION','PRIVATE KEY','SELECT ','race_json','prediction_json'])assert.equal(text.toUpperCase().includes(term.toUpperCase()),false)});
test('settings UI exposes connection check plus race and day URL copy without widening the main cards',async()=>{const [html,app,css]=await Promise.all([readFile(new URL('../index.html',import.meta.url),'utf8'),readFile(new URL('../app.js',import.meta.url),'utf8'),readFile(new URL('../styles.css',import.meta.url),'utf8')]);assert.match(html,/id="publicApiCheck"/);assert.match(html,/id="publicApiCopy"/);assert.match(html,/id="publicApiDayCopy"/);assert.match(app,/currentPublicApiUrl/);assert.match(app,/currentPublicDayApiUrl/);assert.match(css,/\.public-api-actions/)});

test('day-ai suppresses saved market signals when odds are missing and exposes stable aliases',async()=>{
 const pred=prediction('大井','2026-09-01',1);pred.horses[0].odds=null;
 const stored={...row('大井','2026-09-01',1),prediction_json:JSON.stringify(pred),market_json:JSON.stringify({horses:pred.horses})};
 const data=await (await handlePublicApi(request('/api/chass/v1/public/day-ai?date=2026-09-01&track=大井&organization=NAR&format=full'),{DB:new PublicD1([stored])})).json();
 const h=data.races[0].horses[0];
 for(const key of ['odds','popularity','expectedValue','evRank','abilityPopularityGap','diamond','warning','longshot','danger'])assert.equal(h[key],null,key);
 assert.equal(h.horseNumber,h.no);assert.equal(h.horseName,h.name);assert.equal(h.winProb,h.win);assert.equal(h.top3Prob,h.top3);
 assert.deepEqual(h.diamondReasons,[]);assert.deepEqual(h.warningReasons,[]);
});
test('day-ai labels aged saved live odds stale',async()=>{
 const data=await (await handlePublicApi(request('/api/chass/v1/public/day-ai?date=2026-09-01&track=大井&organization=NAR&format=full'),{DB:new PublicD1([row('大井','2026-09-01',1)])})).json();
 assert.equal(data.races[0].horses[0].oddsStatus,'stale');
});
