import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import worker,{parseResult,parseRaceCard,parseTanFuku,parseRuns,predictTimeFromRuns,VERSION,getResearchDb,ensureD1Schema,d1RecordRows,saveD1Record} from './worker.js';
import {resultHtml,raceCardHtml,oddsHtml,debaTableText} from './nar-fixtures.mjs';

async function loadCore(fetchImpl){const source=await readFile(new URL('./app.js',import.meta.url),'utf8'),memory=new Map(),window={__CHASS_TEST__:true};const context={window,console,Date,JSON,Math,Number,String,Array,Object,Map,Set,RegExp,parseFloat,fetch:fetchImpl,localStorage:{getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)}};vm.createContext(context);vm.runInContext(source,context,{filename:'app.js'});return window.CHASS_TEST}
const horses=()=>[
 {horseNo:1,horseName:'一号馬',win:45,place:70,overall:92,ev:110,predictedTime:'1:40.0',predictedTimeType:'実績',predictedTimeScenarios:{standard:'1:40.0',paceFavored:'1:39.4',paceAdverse:'1:40.6'},dataConfidence:90,abilityMark:'◎',odds:2.4,popularity:1},
 {horseNo:2,horseName:'二号馬',win:30,place:58,overall:85,ev:105,predictedTime:'1:40.5',predictedTimeType:'補正',dataConfidence:85,abilityMark:'○',odds:3.5,popularity:2},
 {horseNo:3,horseName:'三号馬',win:20,place:45,overall:80,ev:98,predictedTime:'1:41.0',dataConfidence:80,abilityMark:'▲',odds:5,popularity:3},
 {horseNo:4,horseName:'四号馬',win:5,place:20,overall:60,ev:80,predictedTime:'1:42.0',dataConfidence:70,odds:10,popularity:4}
];
const race=()=>({race:{raceDate:'2026-08-30',track:'船橋',raceNo:4,trackCondition:'良',bias:'',pace:'標準',distance:1500},horses:horses(),predictionSnapshot:{modelVersion:'9.9.3',race:{bias:''},horses:horses().map(({odds,popularity,ev,...prediction})=>prediction)},marketSnapshot:{horses:horses().map(h=>({horseNo:h.horseNo,odds:h.odds,popularity:h.popularity,ev:h.ev}))},finalSnapshot:{top3:[{horseNo:1},{horseNo:2},{horseNo:3}]},resultSnapshot:{finishOrder:[2,3,4,1],actualTimes:{'1':'1:42.0','2':'1:40.7','3':'1:41.2','4':'1:41.5'},horses:horses().map((h,i)=>({horseNo:h.horseNo,position:[4,1,2,3][i],last3f:38+i,finalOdds:[6,4.8,12.4,2.9][i]}))}});

test('version is unified',async()=>{const core=await loadCore(),pkg=JSON.parse(await readFile(new URL('./package.json',import.meta.url)));assert.equal(core.APP_VERSION,'9.9.5');assert.equal(VERSION,pkg.version)});
const longshotField=()=>Array.from({length:12},(_,i)=>({horseNo:i+1,horseName:`馬${i+1}`,win:20-i,place:45-i*2,overall:82-i*2,dataConfidence:75,odds:3+i*2,popularity:i+1,ev:(3+i*2)*Math.max(2,20-i),predictedTime:`1:${String(39+i*.35).padStart(4,'0')}`,predictedTimeType:'実績',features:{distanceFit:65-i,courseFit:62-i,recentFormScore:60},runningStyle:i===7?'逃げ':'差し'}));
test('high EV with low ability is not a longshot',async()=>{const c=await loadCore(),field=longshotField(),h=field[11];h.overall=30;h.win=1;h.place=5;h.ev=500;c.evaluateLongshots(field,{chaos:70,pace:'標準'});assert.equal(h.valueMark,'')});
test('unpopular top TIME horse becomes a supported candidate',async()=>{const c=await loadCore(),field=longshotField(),h=field[7];h.overall=68;h.win=9;h.place=30;h.ev=145;h.predictedTime='1:37.0';h.features={distanceFit:84,courseFit:78,recentFormScore:75};c.evaluateLongshots(field,{chaos:70,pace:'スロー'});assert.ok(h.valueMark);assert.equal(h.timeRank,1);assert.ok(h.longshotReasons.some(x=>x.code==='TIME_TOP'))});
test('ability rank and popularity gap is recorded as evidence',async()=>{const c=await loadCore(),field=longshotField(),h=field[9];h.overall=80;h.win=18;h.place=42;h.ev=160;h.features={distanceFit:85,courseFit:82,recentFormScore:78};c.evaluateLongshots(field,{chaos:60});assert.ok(h.marketGapScore>=35);assert.ok(h.longshotReasons.some(x=>x.code==='MARKET_GAP'))});
test('place longshot is separated from win longshot',async()=>{const c=await loadCore(),field=longshotField(),h=field[8];h.overall=68;h.win=3;h.place=35;h.ev=90;h.features={distanceFit:85,courseFit:82,recentFormScore:78};h.predictedTime='1:37.4';c.evaluateLongshots(field,{chaos:70});assert.equal(h.valueType,'相手穴');assert.equal(h.winValueMark,'');assert.ok(h.placeValueMark)});
test('big longshot requires strong evidence',async()=>{const c=await loadCore(),field=longshotField(),h=field[10];h.overall=60;h.win=5;h.place=20;h.ev=130;h.features={};h.predictedTime='';c.evaluateLongshots(field,{chaos:50});assert.notEqual(h.valueType,'大穴')});
test('longshot snapshot stays frozen after live values change',async()=>{const c=await loadCore(),field=longshotField();c.evaluateLongshots(field,{chaos:70});c.setState({race:{raceDate:'2026-08-30',track:'船橋',raceNo:8},horses:field,predictionSnapshot:null,marketSnapshot:null,finalSnapshot:null,validationCompleted:false});c.makeSnapshot();const before=JSON.stringify(c.getState().predictionSnapshot);field[7].longshotScore=0;field[7].valueMark='';c.getState().validationCompleted=true;c.makeSnapshot();assert.equal(JSON.stringify(c.getState().predictionSnapshot),before)});
test('market reevaluation does not change ability values',async()=>{const c=await loadCore(),field=longshotField(),before=field.map(h=>[h.win,h.place,h.overall]);c.evaluateLongshots(field,{chaos:70});field.forEach((h,i)=>{h.odds+=10;h.ev=h.odds*h.win});c.evaluateLongshots(field,{chaos:70});assert.deepEqual(field.map(h=>[h.win,h.place,h.overall]),before)});
test('HTML has no duplicate IDs',async()=>{const html=await readFile(new URL('./index.html',import.meta.url),'utf8'),ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length)});
test('critical dashboard, backup and cloud controls exist',async()=>{const html=await readFile(new URL('./index.html',import.meta.url),'utf8');for(const id of ['dashboardView','dashKpis','dashModels','dashRaces','recalcDash','exportResearch','researchImportFile','backupStatus','cloudSource','cloudSyncStatus','cloudSyncButton'])assert.match(html,new RegExp(`id="${id}"`))});
test('raceId and TIME conversion are stable',async()=>{const c=await loadCore();assert.equal(c.raceId({raceDate:'2026/08/30',track:'船橋',raceNo:'4R'}),'2026-08-30|船橋|4');assert.equal(c.timeToSec('1:40.3'),100.3)});
test('NAR result fixture parses full order and details',()=>{const r=parseResult(resultHtml);assert.deepEqual(r.finishOrder,['12','11','3','1']);assert.equal(r.results[0].last3f,38.1);assert.equal(r.results[0].cornerPositions,'2-2-1-1');assert.equal(r.results[0].finalOdds,4.8)});
test('card, odds and DebaTable fixtures parse expected fields',()=>{assert.equal(parseRaceCard(raceCardHtml)[1].horseName,'テストホース');assert.equal(parseTanFuku(oddsHtml)[0].popularity,2);const runs=parseRuns(debaTableText,1500,'船橋');assert.equal(runs[0].sameTrack,true);assert.equal(predictTimeFromRuns(runs,1500).scenarios.standard,'1:40.3')});
test('prediction and market snapshots remain frozen',async()=>{const c=await loadCore();c.setState({race:{raceDate:'2026-08-30',track:'船橋',raceNo:4},horses:horses(),predictionSnapshot:null,marketSnapshot:null,finalSnapshot:null,validationCompleted:false});c.makeSnapshot();const before=JSON.stringify(c.getState().predictionSnapshot),market=JSON.stringify(c.getState().marketSnapshot);c.getState().horses[0].win=1;c.getState().validationCompleted=true;c.makeSnapshot();assert.equal(JSON.stringify(c.getState().predictionSnapshot),before);assert.equal(JSON.stringify(c.getState().marketSnapshot),market)});
test('full finish order still treats only first three as TOP3',async()=>{const c=await loadCore(),r=race();assert.equal(c.isTop3(r,1),false);assert.equal(c.isTop3(r,4),true);const a=c.aggregateAdvanced([r]);assert.equal(a.placeMae.length,4)});
test('official place uses field-size rules without changing TOP3',async()=>{const c=await loadCore(),r=race();r.resultSnapshot.finishOrder=[2,3,4,1,5,6,7];assert.equal(c.officialPlaceLimit(r),2);assert.equal(c.isOfficialPlace(r,4),false);assert.equal(c.isTop3(r,4),true);r.resultSnapshot.finishOrder.push(8);assert.equal(c.officialPlaceLimit(r),3);assert.equal(c.isOfficialPlace(r,4),true)});
test('Wilson interval is bounded and contains observed rate',async()=>{const c=await loadCore(),ci=c.wilsonInterval(5,10);assert.ok(ci.low>=0&&ci.high<=100);assert.ok(ci.low<50&&ci.high>50);assert.equal(c.wilsonInterval(0,0),null)});
test('model ROI uses only official settled win odds',async()=>{const c=await loadCore(),r=race(),m=c.modelPerformance([r],()=>c.frozenHorses(r).find(h=>h.horseNo===2));assert.equal(m.roiN,1);assert.equal(m.roiWins,1);assert.equal(m.roi,480)});
test('missing settled odds are excluded rather than counted as zero return',async()=>{const c=await loadCore(),r=race();delete r.resultSnapshot.horses.find(h=>h.horseNo===2).finalOdds;const m=c.modelPerformance([r],()=>c.frozenHorses(r).find(h=>h.horseNo===2));assert.equal(m.target,1);assert.equal(m.roiN,0);assert.equal(m.roi,null)});
test('snapshot fingerprint is canonical for object key order',async()=>{const c=await loadCore();assert.equal(c.snapshotFingerprint({b:2,a:{d:4,c:3}}),c.snapshotFingerprint({a:{c:3,d:4},b:2}))});
test('sealed snapshot detects later prediction mutation',async()=>{const c=await loadCore(),r=race();c.sealSnapshotIntegrity(r,true);assert.equal(c.verifySnapshotIntegrity(r).status,'verified');r.predictionSnapshot.horses[0].win=1;const audit=c.verifySnapshotIntegrity(r);assert.equal(audit.status,'invalid');assert.equal(audit.mismatches.join(','),'predictionSnapshot')});
test('temporal leakage guard rejects result acquired before prediction',async()=>{const c=await loadCore(),r=race();r.predictionSnapshot.createdAt='2026-08-30T10:00:00Z';r.resultSnapshot.fetchedAt='2026-08-30T09:00:00Z';c.sealSnapshotIntegrity(r,true);assert.equal(c.verifySnapshotIntegrity(r).temporalInvalid,true);assert.equal(c.validationQuality(r).grade,'C')});
test('position discrepancy is a check rather than a failure',async()=>{const c=await loadCore(),r=race();r.predictionSnapshot.horses[0].runningStyle='逃げ・先行';r.resultSnapshot.finishOrder=[2,3,4,1,5,6,7,8,9,10];r.resultSnapshot.horses.find(h=>h.horseNo===1).cornerPositions='9-8-7-4';const d=c.diagnosticsForRace(r);assert.equal(d.checks.some(x=>x.code==='POSITION_CHECK'),true);assert.equal(d.failures.some(x=>x.code==='POSITION_CHECK'),false)});
test('value type ROI uses settled odds and records its sample',async()=>{const c=await loadCore(),r=race(),m=r.marketSnapshot.horses.find(h=>h.horseNo===2);m.valueMark='💎';m.winValueFlag='💎';const g=c.aggregateAdvanced([r]).valueTypes['勝ち穴'];assert.equal(g.roiN,1);assert.equal(g.roiWins,1);assert.equal(g.roiReturn,4.8)});
test('single high-probability loss is a check, not overrating failure',async()=>{const c=await loadCore(),d=c.diagnosticsForRace(race());assert.equal(d.failures.some(x=>x.code==='PROB_OVER'),false);assert.equal(d.checks.some(x=>x.code==='PROB_CHECK'),true)});
test('track condition alone is not bias failure or check',async()=>{const c=await loadCore(),d=c.diagnosticsForRace(race());assert.equal([...d.failures,...d.checks].some(x=>x.code==='BIAS_CHECK'),false)});
test('calibration and TIME metrics use frozen predictions',async()=>{const c=await loadCore(),a=c.aggregateAdvanced([race()]);assert.ok(Object.keys(a.winCalibration).length>0);assert.equal(a.timeError.length,4);assert.equal(a.timeByType['実績'].length,1);assert.equal(a.timeByType['補正'].length,1)});
test('validation quality never converts missing data to successful zero',async()=>{const c=await loadCore(),r=race();r.marketSnapshot={horses:[]};const q=c.validationQuality(r);assert.equal(q.grade,'B');assert.equal(q.issues.some(x=>x.code==='MARKET_MISSING'),true)});
test('same race ID updates one cache record',async()=>{const c=await loadCore(),id='2026-08-30|船橋|4';c.saveRaceRecord(id,{updatedAt:'2026-08-30T00:00:00Z'});c.saveRaceRecord(id,{validated:true,updatedAt:'2026-08-30T01:00:00Z'});assert.equal(Object.keys(c.getRaceCache()).length,1);assert.equal(c.getRaceCache()[id].validated,true)});
test('legacy migration is idempotent and preserves horses',async()=>{const c=await loadCore(),r={race:{raceDate:'2026-08-30',track:'船橋',raceNo:4},horses:horses()},before=JSON.stringify(r.horses);assert.equal(c.migrateSnapshotRecord(r),true);assert.equal(JSON.stringify(r.horses),before);assert.equal(c.migrateSnapshotRecord(r),false)});
test('IndexedDB unavailable falls back without deleting local data',async()=>{const c=await loadCore();await c.initResearchStorage();assert.equal(c.getStorageMode(),'localStorage-fallback')});
test('research backup validates and preserves its schema',async()=>{const c=await loadCore(),backup=c.createResearchBackup(),meta=c.validateResearchBackup(backup);assert.equal(backup.format,'CHASS_KEIBA_RESEARCH_BACKUP');assert.equal(meta.schemaVersion,c.BACKUP_SCHEMA_VERSION);assert.throws(()=>c.validateResearchBackup({...backup,schemaVersion:99}),/新しい形式/)});
test('backup merge never overwrites a newer local race',async()=>{const c=await loadCore(),local=race(),incoming=race(),id='2026-08-30|船橋|4';local.updatedAt='2026-08-30T10:00:00Z';incoming.updatedAt='2026-08-30T09:00:00Z';const result=c.mergeResearchBackup({format:'CHASS_KEIBA_RESEARCH_BACKUP',schemaVersion:1,races:{[id]:incoming}},{[id]:local});assert.equal(result.imported,0);assert.equal(result.skipped,1);assert.equal(result.merged[id].updatedAt,local.updatedAt)});
test('backup merge adds a new race and migration timestamps',async()=>{const c=await loadCore(),incoming=race(),id='2026-08-30|船橋|4';incoming.updatedAt='2026-08-30T09:00:00Z';incoming.predictionSnapshot.createdAt='2026-08-30T08:00:00Z';incoming.resultSnapshot.fetchedAt='2026-08-30T09:00:00Z';const result=c.mergeResearchBackup({format:'CHASS_KEIBA_RESEARCH_BACKUP',schemaVersion:1,races:{[id]:incoming}},{});assert.equal(result.imported,1);assert.equal(result.merged[id].predictionCreatedAt,'2026-08-30T08:00:00Z');assert.equal(result.merged[id].resultAcquiredAt,'2026-08-30T09:00:00Z')});

class FakeD1{
 constructor(){this.races=new Map();this.predictions=new Set();this.results=new Set();this.failHealth=false}
 prepare(sql){const db=this,statement={sql,args:[],bind(...args){this.args=args;return this},async first(){if(db.failHealth)throw new Error('D1 unavailable');return {ok:1}},async all(){return {results:[]}}};return statement}
 async batch(statements){for(const s of statements){if(/^INSERT INTO races/i.test(s.sql)){const key=`${s.args[0]}|${s.args[1]}`;if(!this.races.has(key))this.races.set(key,{prediction:s.args[3],result:s.args[6]});else this.races.get(key).result=s.args[6]}else if(/^INSERT OR IGNORE INTO predictions/i.test(s.sql))this.predictions.add(`${s.args[0]}|${s.args[1]}|${s.args[2]}`);else if(/^INSERT INTO results/i.test(s.sql))this.results.add(`${s.args[0]}|${s.args[1]}`)}return statements.map(()=>({success:true}))}
}
test('D1 binding uses the Cloudflare DB binding',()=>{const db=new FakeD1();assert.equal(getResearchDb({DB:db}),db);assert.equal(getResearchDb({'chass-keiba-lab-db':db}),null)});
test('D1 schema defines races predictions and results without deletes',async()=>{const sql=await readFile(new URL('./d1-schema.sql',import.meta.url),'utf8');for(const table of ['races','predictions','results'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.doesNotMatch(sql,/\bDELETE\b/i)});
test('DB health reports connected and missing binding safely',async()=>{const db=new FakeD1(),ok=await worker.fetch(new Request('https://example.com/api/db/health'),{DB:db}),missing=await worker.fetch(new Request('https://example.com/api/db/health'),{});assert.equal((await ok.json()).database,'connected');assert.equal(missing.status,503);assert.equal((await missing.json()).error,'d1_binding_unavailable')});
test('DB health classifies SELECT failure as d1_query_failed',async()=>{const db=new FakeD1();db.failHealth=true;const response=await worker.fetch(new Request('https://example.com/api/db/health'),{DB:db});assert.equal(response.status,503);assert.equal((await response.json()).error,'d1_query_failed')});
test('D1 schema initialization failure is classified',async()=>{const db=new FakeD1();db.batch=async()=>{throw new Error('schema denied')};await assert.rejects(()=>ensureD1Schema(db),error=>error.code==='d1_schema_error')});
test('D1 row mapping stores required prediction and result fields',()=>{const r=race(),rows=d1RecordRows('2026-08-30|船橋|4',r),p=rows.predictions[0],x=rows.results[0];assert.equal(p.aiWinRate,45);assert.equal(p.aiPlaceRate,70);assert.equal(p.predictedTime,'1:40.0');assert.equal(x.actualTime,'1:42.0');assert.equal(x.final3F,38)});
test('D1 duplicate sync does not duplicate predictions or results',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);await saveD1Record(db,id,r);assert.equal(db.races.size,1);assert.equal(db.predictions.size,4);assert.equal(db.results.size,4)});
test('D1 result update never overwrites immutable prediction snapshot',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);const key=`${id}|9.9.3`,before=db.races.get(key).prediction;r.predictionSnapshot.horses[0].win=1;r.resultSnapshot.finishOrder=[1,2,3,4];await saveD1Record(db,id,r);assert.equal(db.races.get(key).prediction,before);assert.equal(JSON.parse(before).horses[0].win,45)});
test('stale prediction-only sync cannot clear an existing cloud result',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);const capture=db.prepare.bind(db);let raceSql='';db.prepare=sql=>{if(/^INSERT INTO races/i.test(sql))raceSql=sql;return capture(sql)};const stale=race();stale.resultSnapshot=null;await saveD1Record(db,id,stale);assert.match(raceSql,/result_json=COALESCE\(excluded\.result_json,races\.result_json\)/)});
test('D1 failure keeps frontend in local fallback mode',async()=>{const c=await loadCore(async()=>new Response(JSON.stringify({ok:false,error:'d1_binding_unavailable'}),{status:503,headers:{'content-type':'application/json'}}));assert.equal(await c.initCloudResearch(),false);assert.equal(c.getCloudState().source,'local')});
