import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import worker,{parseResult,parseRaceCard,parseTanFuku,parseRuns,predictTimeFromRuns,fetchNarResultWithRetry,fetchNarResultResilient,fetchNarRaceSources,buildNarRacePayload,minimalJson,VERSION,getResearchDb,ensureD1Schema,d1RecordRows,d1SyncDescriptor,readD1Manifest,readD1ResearchDataset,saveD1Record} from './worker.js';
import {resultHtml,raceCardHtml,oddsHtml,debaTableText} from './nar-fixtures.mjs';

async function loadCore(fetchImpl){const source=await readFile(new URL('./app.js',import.meta.url),'utf8'),memory=new Map(),window={__CHASS_TEST__:true};const context={window,console,Date,JSON,Math,Number,String,Array,Object,Map,Set,RegExp,TextEncoder,AbortController,parseFloat,fetch:fetchImpl,localStorage:{getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)}};vm.createContext(context);vm.runInContext(source,context,{filename:'app.js'});return window.CHASS_TEST}
const horses=()=>[
 {horseNo:1,horseName:'一号馬',win:45,place:70,overall:92,ev:110,predictedTime:'1:40.0',predictedTimeType:'実績',predictedTimeScenarios:{standard:'1:40.0',paceFavored:'1:39.4',paceAdverse:'1:40.6'},dataConfidence:90,abilityMark:'◎',odds:2.4,popularity:1},
 {horseNo:2,horseName:'二号馬',win:30,place:58,overall:85,ev:105,predictedTime:'1:40.5',predictedTimeType:'補正',dataConfidence:85,abilityMark:'○',odds:3.5,popularity:2},
 {horseNo:3,horseName:'三号馬',win:20,place:45,overall:80,ev:98,predictedTime:'1:41.0',dataConfidence:80,abilityMark:'▲',odds:5,popularity:3},
 {horseNo:4,horseName:'四号馬',win:5,place:20,overall:60,ev:80,predictedTime:'1:42.0',dataConfidence:70,odds:10,popularity:4}
];
const race=()=>({race:{raceDate:'2026-08-30',track:'船橋',raceNo:4,trackCondition:'良',bias:'',pace:'標準',distance:1500},horses:horses(),predictionSnapshot:{modelVersion:'9.9.3',race:{bias:''},horses:horses().map(({odds,popularity,ev,...prediction})=>prediction)},marketSnapshot:{horses:horses().map(h=>({horseNo:h.horseNo,odds:h.odds,popularity:h.popularity,ev:h.ev}))},finalSnapshot:{top3:[{horseNo:1},{horseNo:2},{horseNo:3}]},resultSnapshot:{finishOrder:[2,3,4,1],actualTimes:{'1':'1:42.0','2':'1:40.7','3':'1:41.2','4':'1:41.5'},horses:horses().map((h,i)=>({horseNo:h.horseNo,position:[4,1,2,3][i],last3f:38+i,finalOdds:[6,4.8,12.4,2.9][i]}))}});

test('version is unified',async()=>{const core=await loadCore(),pkg=JSON.parse(await readFile(new URL('./package.json',import.meta.url)));assert.equal(core.APP_VERSION,'9.9.20');assert.equal(VERSION,pkg.version)});

test('post-fetch failure is separated from successful NAR acquisition',async()=>{const src=await readFile(new URL('./app.js',import.meta.url),'utf8');assert.match(src,/resultFetchSuccess:true,postFetchAudit:\{success:false/);assert.match(src,/persist_failed/);assert.match(src,/結果取得成功：/)});
test('NAR result retry succeeds on second attempt after network error',async()=>{let calls=0;const fetcher=async()=>{calls++;if(calls===1)throw Object.assign(new TypeError('fetch failed'),{code:'network_error'});return '<html>ok</html>'},r=await fetchNarResultWithRetry('https://example.test',{fetcher,sleeper:async()=>{}});assert.equal(r.attemptCount,2);assert.equal(calls,2)});
test('NAR result retry succeeds on third attempt after two transient errors',async()=>{let calls=0;const fetcher=async()=>{calls++;if(calls<3)throw Object.assign(new Error('temporary'),{status:503});return '<html>ok</html>'},r=await fetchNarResultWithRetry('https://example.test',{fetcher,sleeper:async()=>{}});assert.equal(r.attemptCount,3);assert.equal(calls,3)});
test('NAR result retry stops after three network failures',async()=>{let calls=0;const fetcher=async()=>{calls++;throw Object.assign(new TypeError('fetch failed'),{code:'network_error'})};await assert.rejects(fetchNarResultWithRetry('https://example.test',{fetcher,sleeper:async()=>{}}),e=>e.code==='network_error'&&e.attemptCount===3);assert.equal(calls,3)});
test('NAR result retry does not repeat 404 or parser error',async()=>{for(const error of [Object.assign(new Error('not found'),{status:404}),Object.assign(new Error('parse failed'),{code:'parser_error'})]){let calls=0;await assert.rejects(fetchNarResultWithRetry('https://example.test',{fetcher:async()=>{calls++;throw error},sleeper:async()=>{}}));assert.equal(calls,1)}});
test('NAR result resilience falls back to IPAT after two primary network failures',async()=>{const calls=[];const fetcher=async url=>{calls.push(url);if(url.includes('/KeibaWeb/'))throw Object.assign(new TypeError('fetch failed'),{code:'network_error'});return resultHtml};const r=await fetchNarResultResilient('https://example.test/KeibaWeb/result','https://example.test/KeibaWeb_IPAT/result',{fetcher,sleeper:async()=>{}});assert.equal(r.urlType,'RaceMarkTable_ipat');assert.equal(r.fallbackUsed,true);assert.deepEqual(r.parsed.finishOrder.slice(0,3),['12','11','3']);assert.equal(calls.filter(x=>x.includes('/KeibaWeb/')).length,2);assert.equal(calls.filter(x=>x.includes('/KeibaWeb_IPAT/')).length,1)});
test('NAR result resilience tries IPAT when primary returns an unparseable 200 page',async()=>{let calls=0;const fetcher=async url=>{calls++;return url.includes('/KeibaWeb_IPAT/')?resultHtml:'<html><body>temporary page</body></html>'};const r=await fetchNarResultResilient('https://example.test/KeibaWeb/result','https://example.test/KeibaWeb_IPAT/result',{fetcher,sleeper:async()=>{}});assert.equal(r.urlType,'RaceMarkTable_ipat');assert.equal(r.fallbackUsed,true);assert.equal(r.parsed.finishOrder.length>=3,true);assert.equal(calls,2)});
const raceUrls={detail:'https://test/DebaTableSmall',card:'https://test/RaceMarkTable',cardFallback:'https://test/RaceMarkTable_ipat',odds:'https://test/OddsTanFuku'};
test('race fetch succeeds when detail card and odds all succeed',async()=>{const r=await fetchNarRaceSources(raceUrls,{fetcher:async url=>url.includes('Odds')?oddsHtml:raceCardHtml,sleeper:async()=>{}});assert.equal(r.audit.detail.success,true);assert.equal(r.audit.card.success,true);assert.equal(r.audit.odds.success,true)});
test('detail success keeps race acquisition viable when both card routes fail',async()=>{const r=await fetchNarRaceSources(raceUrls,{fetcher:async url=>{if(url.includes('RaceMark'))throw Object.assign(new TypeError('down'),{code:'network_error'});return url.includes('Odds')?oddsHtml:raceCardHtml},sleeper:async()=>{}});assert.equal(r.audit.detail.success,true);assert.equal(r.audit.card.success,false);assert.ok(r.detailHtml)});
test('RaceMarkTable IPAT fallback recovers the optional card',async()=>{const r=await fetchNarRaceSources(raceUrls,{fetcher:async url=>{if(url.endsWith('RaceMarkTable'))throw Object.assign(new TypeError('down'),{code:'network_error'});return url.includes('Odds')?oddsHtml:raceCardHtml},sleeper:async()=>{}});assert.equal(r.audit.card.success,true);assert.equal(r.audit.card.fallbackUsed,true);assert.equal(r.audit.card.activeRoute,'RaceMarkTable_ipat')});
test('odds failure is optional for race acquisition',async()=>{const r=await fetchNarRaceSources(raceUrls,{fetcher:async url=>{if(url.includes('Odds'))throw Object.assign(new Error('timeout'),{code:'nar_timeout'});return raceCardHtml},sleeper:async()=>{}});assert.equal(r.audit.detail.success,true);assert.equal(r.audit.odds.success,false);assert.equal(r.audit.odds.optional,true)});
test('card can supply horses when DebaTableSmall fails',async()=>{const payload=await buildNarRacePayload({code:'20',date:'2026-08-31',race:'1',urls:raceUrls,fetcher:async url=>{if(url.includes('Deba'))throw Object.assign(new TypeError('down'),{code:'network_error'});return url.includes('Odds')?oddsHtml:raceCardHtml},sleeper:async()=>{}});assert.equal(payload.raceSuccess,true);assert.ok(payload.horses.length>=2);assert.equal(payload.quality.parser,'RaceMarkTable-fallback')});
test('race diagnostic route and recovery promotion UI are present',async()=>{const workerSource=await readFile(new URL('./worker.js',import.meta.url),'utf8'),appSource=await readFile(new URL('./app.js',import.meta.url),'utf8');assert.match(workerSource,/api\/nar\/race-diagnostic/);assert.match(appSource,/race-diagnostic/);assert.match(appSource,/診断復旧で予想保存済/)});
test('intentional race request abort is not labeled network_error',async()=>{const appSource=await readFile(new URL('./app.js',import.meta.url),'utf8');assert.match(appSource,/signal\?\.aborted\?'aborted':'timeout'/);assert.match(appSource,/e\?\.code==='aborted'/)});
test('result check is asynchronous and cannot erase prediction success',async()=>{const appSource=await readFile(new URL('./app.js',import.meta.url),'utf8');assert.match(appSource,/commitAutoRaceData\(d/);assert.match(appSource,/Promise\.resolve\(\)\.then\(\(\)=>syncNar/);assert.match(appSource,/予想取得成功・結果確認のみ再試行可/)});
test('minimal result API succeeds without odds and stays below 50KB',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response(resultHtml,{status:200});try{const response=await worker.fetch(new Request('https://example.test/api/nar/sync-minimal?code=20&date=2026-08-13&race=8'),{}),body=await response.json();assert.equal(body.ok,true);assert.equal(body.resultSuccess,true);assert.deepEqual(body.finishOrder,[12,11,3]);assert.ok(body.payloadBytes<50000);assert.ok(body.audit.narFetchMs>=0);assert.equal('odds' in body,false);assert.equal(response.headers.get('cache-control'),'no-store')}finally{globalThis.fetch=original}});
test('minimal result API promotes IPAT fallback',async()=>{const original=globalThis.fetch;globalThis.fetch=async url=>{if(String(url).includes('/KeibaWeb/'))throw Object.assign(new TypeError('down'),{code:'network_error'});return new Response(resultHtml,{status:200})};try{const body=await (await worker.fetch(new Request('https://example.test/api/nar/sync-minimal?code=20&date=2026-08-13&race=8'),{})).json();assert.equal(body.ok,true);assert.equal(body.fallbackUsed,true);assert.equal(body.source,'RaceMarkTable_ipat')}finally{globalThis.fetch=original}});
test('Safari transport separates HTTP 200 body read failure',async()=>{const c=await loadCore(async()=>({ok:true,status:200,text:async()=>{throw new Error('stream interrupted')}}));await assert.rejects(c.fetchNarMinimalApi('/api/test'),e=>e.code==='response_body_failed'&&e.transportAudit.headers.httpStatus===200)});
test('Safari transport separates malformed JSON',async()=>{const c=await loadCore(async()=>new Response('<html>broken</html>',{status:200}));await assert.rejects(c.fetchNarMinimalApi('/api/test'),e=>e.code==='json_parse_failed'&&e.transportAudit.body.success===true)});
test('Safari transport separates HTTP error',async()=>{const c=await loadCore(async()=>new Response(JSON.stringify({ok:false,errorCode:'http_error',error:'upstream'}),{status:500}));await assert.rejects(c.fetchNarMinimalApi('/api/test'),e=>e.code==='http_error'&&e.status===500)});
test('Safari transport separates AbortController cancellation',async()=>{const controller=new AbortController();controller.abort();const c=await loadCore(async()=>{throw Object.assign(new Error('aborted'),{name:'AbortError'})});await assert.rejects(c.fetchNarMinimalApi('/api/test',{signal:controller.signal}),e=>e.code==='fetch_aborted')});
test('Safari transport separates stale generation',async()=>{const c=await loadCore(async()=>new Response(JSON.stringify({ok:true,finishOrder:[1,2,3]}),{status:200}));await assert.rejects(c.fetchNarMinimalApi('/api/test',{generation:1,isCurrent:()=>false}),e=>e.code==='stale_request')});
test('minimal serializer classifies circular payload',async()=>{const circular={ok:true};circular.self=circular;const response=minimalJson(circular),body=await response.json();assert.equal(response.status,500);assert.equal(body.errorCode,'serialize_failed')});
test('minimal route leaves odds and D1 outside NAR response',async()=>{const source=await readFile(new URL('./worker.js',import.meta.url),'utf8'),appSource=await readFile(new URL('./app.js',import.meta.url),'utf8');assert.match(appSource,/api\/nar\/sync-minimal/);assert.match(source,/u\.pathname==="\/api\/nar\/sync-minimal"/);assert.doesNotMatch(source.match(/if\(u\.pathname==="\/api\/nar\/sync-minimal"\)[\s\S]*?\n  }\n/)?.[0]||'',/saveD1Record|OddsTanFuku/)});
test('unpublished result page remains pending instead of network error',()=>{const parsed=parseResult('<html><table><tr><th>着順</th><th>馬番</th><th>馬名</th></tr></table></html>');assert.equal(parsed.finishOrder.length,0)});
test('saved result remains fetched when a retry later fails',async()=>{const c=await loadCore(),r=race();r.resultStatus='fetched';r.resultFetchError='network failed';const display=c.getResultDisplayState(r);assert.equal(display.done,true);assert.equal(display.status,'fetched');assert.equal(display.label,'取得済｜再取得失敗');assert.deepEqual(display.finishOrder,[2,3,4])});
const longshotField=()=>Array.from({length:12},(_,i)=>({horseNo:i+1,horseName:`馬${i+1}`,win:20-i,place:45-i*2,overall:82-i*2,dataConfidence:75,odds:3+i*2,popularity:i+1,ev:(3+i*2)*Math.max(2,20-i),predictedTime:`1:${String(39+i*.35).padStart(4,'0')}`,predictedTimeType:'実績',features:{distanceFit:65-i,courseFit:62-i,recentFormScore:60},runningStyle:i===7?'逃げ':'差し'}));
test('high EV with low ability is not a longshot',async()=>{const c=await loadCore(),field=longshotField(),h=field[11];h.overall=30;h.win=1;h.place=5;h.ev=500;c.evaluateLongshots(field,{chaos:70,pace:'標準'});assert.equal(h.valueMark,'')});
test('unpopular top TIME horse becomes a supported candidate',async()=>{const c=await loadCore(),field=longshotField(),h=field[7];h.overall=68;h.win=9;h.place=30;h.ev=145;h.predictedTime='1:37.0';h.features={distanceFit:84,courseFit:78,recentFormScore:75};c.evaluateLongshots(field,{chaos:70,pace:'スロー'});assert.ok(h.valueMark);assert.equal(h.timeRank,1);assert.ok(h.longshotReasons.some(x=>x.code==='TIME_TOP'))});
test('ability rank and popularity gap is recorded as evidence',async()=>{const c=await loadCore(),field=longshotField(),h=field[9];h.overall=80;h.win=18;h.place=42;h.ev=160;h.features={distanceFit:85,courseFit:82,recentFormScore:78};c.evaluateLongshots(field,{chaos:60});assert.ok(h.marketGapScore>=35);assert.ok(h.longshotReasons.some(x=>x.code==='MARKET_GAP'))});
test('place longshot is separated from win longshot',async()=>{const c=await loadCore(),field=longshotField(),h=field[8];h.overall=68;h.win=3;h.place=35;h.ev=90;h.features={distanceFit:85,courseFit:82,recentFormScore:78};h.predictedTime='1:37.4';c.evaluateLongshots(field,{chaos:70});assert.equal(h.valueType,'相手穴');assert.equal(h.winValueMark,'');assert.ok(h.placeValueMark)});
test('big longshot requires strong evidence',async()=>{const c=await loadCore(),field=longshotField(),h=field[10];h.overall=60;h.win=5;h.place=20;h.ev=130;h.features={};h.predictedTime='';c.evaluateLongshots(field,{chaos:50});assert.notEqual(h.valueType,'大穴')});
test('longshot snapshot stays frozen after live values change',async()=>{const c=await loadCore(),field=longshotField();c.evaluateLongshots(field,{chaos:70});c.setState({race:{raceDate:'2026-08-30',track:'船橋',raceNo:8},horses:field,predictionSnapshot:null,marketSnapshot:null,finalSnapshot:null,validationCompleted:false});c.makeSnapshot();const before=JSON.stringify(c.getState().predictionSnapshot);field[7].longshotScore=0;field[7].valueMark='';c.getState().validationCompleted=true;c.makeSnapshot();assert.equal(JSON.stringify(c.getState().predictionSnapshot),before)});
test('market reevaluation does not change ability values',async()=>{const c=await loadCore(),field=longshotField(),before=field.map(h=>[h.win,h.place,h.overall]);c.evaluateLongshots(field,{chaos:70});field.forEach((h,i)=>{h.odds+=10;h.ev=h.odds*h.win});c.evaluateLongshots(field,{chaos:70});assert.deepEqual(field.map(h=>[h.win,h.place,h.overall]),before)});
test('HTML has no duplicate IDs',async()=>{const html=await readFile(new URL('./index.html',import.meta.url),'utf8'),ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length)});
test('critical dashboard, backup and cloud controls exist',async()=>{const html=await readFile(new URL('./index.html',import.meta.url),'utf8');for(const id of ['dashboardView','dashKpis','dashModels','dashRaces','recalcDash','exportResearch','researchImportFile','backupStatus','cloudSource','cloudSyncStatus','cloudSyncButton','cloudRestoreButton','cloudDatasetSummary','cloudExclusionList'])assert.match(html,new RegExp(`id="${id}"`))});
test('raceId and TIME conversion are stable',async()=>{const c=await loadCore();assert.equal(c.raceId({raceDate:'2026/08/30',track:'船橋',raceNo:'4R'}),'2026-08-30|船橋|4');assert.equal(c.timeToSec('1:40.3'),100.3)});
test('NAR result fixture parses full order and details',()=>{const r=parseResult(resultHtml);assert.deepEqual(r.finishOrder,['12','11','3','1']);assert.equal(r.results[0].last3f,38.1);assert.equal(r.results[0].cornerPositions,'2-2-1-1');assert.equal(r.results[0].finalOdds,4.8)});
test('card, odds and DebaTable fixtures parse expected fields',()=>{assert.equal(parseRaceCard(raceCardHtml)[1].horseName,'テストホース');assert.equal(parseTanFuku(oddsHtml)[0].popularity,2);const runs=parseRuns(debaTableText,1500,'船橋');assert.equal(runs[0].sameTrack,true);assert.equal(predictTimeFromRuns(runs,1500).scenarios.standard,'1:40.3')});
test('prediction and market snapshots remain frozen',async()=>{const c=await loadCore();c.setState({race:{raceDate:'2026-08-30',track:'船橋',raceNo:4},horses:horses(),predictionSnapshot:null,marketSnapshot:null,finalSnapshot:null,validationCompleted:false});c.makeSnapshot();const before=JSON.stringify(c.getState().predictionSnapshot),market=JSON.stringify(c.getState().marketSnapshot);c.getState().horses[0].win=1;c.getState().validationCompleted=true;c.makeSnapshot();assert.equal(JSON.stringify(c.getState().predictionSnapshot),before);assert.equal(JSON.stringify(c.getState().marketSnapshot),market)});
test('full finish order still treats only first three as TOP3',async()=>{const c=await loadCore(),r=race();assert.equal(c.isTop3(r,1),false);assert.equal(c.isTop3(r,4),true);const a=c.aggregateAdvanced([r]);assert.equal(a.placeMae.length,4)});
test('official place uses field-size rules without changing TOP3',async()=>{const c=await loadCore(),r=race();r.resultSnapshot.finishOrder=[2,3,4,1,5,6,7];assert.equal(c.officialPlaceLimit(r),2);assert.equal(c.isOfficialPlace(r,4),false);assert.equal(c.isTop3(r,4),true);r.resultSnapshot.finishOrder.push(8);assert.equal(c.officialPlaceLimit(r),3);assert.equal(c.isOfficialPlace(r,4),true)});
test('Wilson interval is bounded and contains observed rate',async()=>{const c=await loadCore(),ci=c.wilsonInterval(5,10);assert.ok(ci.low>=0&&ci.high<=100);assert.ok(ci.low<50&&ci.high>50);assert.equal(c.wilsonInterval(0,0),null)});
test('model ROI uses only official settled win odds',async()=>{const c=await loadCore(),r=race(),m=c.modelPerformance([r],()=>c.frozenHorses(r).find(h=>h.horseNo===2));assert.equal(m.roiN,1);assert.equal(m.roiWins,1);assert.equal(m.roi,480)});
test('missing settled odds are excluded rather than counted as zero return',async()=>{const c=await loadCore(),r=race();delete r.resultSnapshot.horses.find(h=>h.horseNo===2).finalOdds;const m=c.modelPerformance([r],()=>c.frozenHorses(r).find(h=>h.horseNo===2));assert.equal(m.target,1);assert.equal(m.roiN,0);assert.equal(m.roi,null)});
test('snapshot fingerprint is canonical for object key order',async()=>{const c=await loadCore();assert.equal(c.snapshotFingerprint({b:2,a:{d:4,c:3}}),c.snapshotFingerprint({a:{c:3,d:4},b:2}))});
test('sealed snapshot detects later prediction mutation',async()=>{const c=await loadCore(),r=race();c.sealSnapshotIntegrity(r,true);assert.equal(c.verifySnapshotIntegrity(r).status,'verified');r.predictionSnapshot.horses[0].win=1;const audit=c.verifySnapshotIntegrity(r);assert.equal(audit.status,'invalid');assert.equal(audit.mismatches.join(','),'predictionSnapshot')});
test('temporal leakage guard rejects result acquired before prediction',async()=>{const c=await loadCore(),r=race();r.predictionSnapshot.createdAt='2026-08-30T10:00:00Z';r.resultSnapshot.fetchedAt='2026-08-30T09:00:00Z';c.sealSnapshotIntegrity(r,true);assert.equal(c.verifySnapshotIntegrity(r).temporalInvalid,true);assert.equal(c.validationQuality(r).grade,'C')});
test('position discrepancy is a check rather than a failure',async()=>{const c=await loadCore(),r=race();r.predictionSnapshot.horses[0].runningStyle='逃げ・先行';r.resultSnapshot.finishOrder=[2,3,4,1,5,6,7,8,9,10];r.resultSnapshot.horses.find(h=>h.horseNo===1).cornerPositions='9-8-7-4';const d=c.diagnosticsForRace(r);assert.equal(d.checks.some(x=>x.code==='POSITION_CHECK'),true);assert.equal(d.failures.some(x=>x.code==='POSITION_CHECK'),false)});
test('value type ROI uses settled odds and records its sample',async()=>{const c=await loadCore(),r=race(),m=r.marketSnapshot.horses.find(h=>h.horseNo===2);m.valueMark='💎';m.winValueFlag='💎';const g=c.aggregateAdvanced([r]).valueTypes['勝ち穴'];assert.equal(g.roiN,1);assert.equal(g.roiWins,1);assert.equal(g.roiReturn,4.8)});
test('single high-probability loss is a check, not overrating failure',async()=>{const c=await loadCore(),d=c.diagnosticsForRace(race());assert.equal(d.failures.some(x=>x.code==='PROB_OVER'),false);assert.equal(d.checks.some(x=>x.code==='PROB_CHECK'),true)});
test('track condition alone is not bias failure or check',async()=>{const c=await loadCore(),d=c.diagnosticsForRace(race());assert.equal([...d.failures,...d.checks].some(x=>x.code==='BIAS_CHECK'),false)});
test('calibration and TIME metrics use frozen predictions',async()=>{const c=await loadCore(),a=c.aggregateAdvanced([race()]);assert.ok(Object.keys(a.winCalibration).length>0);assert.equal(a.timeError.length,4);assert.equal(a.timeByType['実績'].length,1);assert.equal(a.timeByType['補正'].length,1)});
test('validation quality never converts missing data to successful zero',async()=>{const c=await loadCore(),r=race();r.marketSnapshot={horses:[]};const q=c.validationQuality(r);assert.equal(q.grade,'B');assert.equal(q.issues.some(x=>x.code==='MARKET_MISSING'),true)});
test('same race ID updates one cache record',async()=>{const c=await loadCore(),id='2026-08-30|船橋|4';c.saveRaceRecord(id,{updatedAt:'2026-08-30T00:00:00Z'});c.saveRaceRecord(id,{validated:true,updatedAt:'2026-08-30T01:00:00Z'});assert.equal(Object.keys(c.getRaceCache()).length,1);assert.equal(c.getRaceCache()[id].validated,true)});
test('legacy migration is idempotent and preserves horses',async()=>{const c=await loadCore(),r={race:{raceDate:'2026-08-30',track:'船橋',raceNo:4},horses:horses()},before=JSON.stringify(r.horses);assert.equal(c.migrateSnapshotRecord(r),true);assert.equal(JSON.stringify(r.horses),before);assert.equal(c.migrateSnapshotRecord(r),false)});
test('IndexedDB unavailable falls back without deleting local data',async()=>{const c=await loadCore();await c.initResearchStorage();assert.equal(c.getStorageMode(),'localStorage-fallback')});
test('research backup validates and preserves its schema',async()=>{const c=await loadCore(),backup=c.createResearchBackup(),meta=c.validateResearchBackup(backup);assert.equal(backup.format,'CHASS_KEIBA_RESEARCH_BACKUP');assert.equal(meta.schemaVersion,c.BACKUP_SCHEMA_VERSION);assert.throws(()=>c.validateResearchBackup({...backup,schemaVersion:99}),/新しい形式/)});
test('backup merge never overwrites a newer local race',async()=>{const c=await loadCore(),local=race(),incoming=race(),id='2026-08-30|船橋|4';local.updatedAt='2026-08-30T10:00:00Z';incoming.updatedAt='2026-08-30T09:00:00Z';const result=c.mergeResearchBackup({format:'CHASS_KEIBA_RESEARCH_BACKUP',schemaVersion:1,races:{[id]:incoming}},{[id]:local});assert.equal(result.imported,0);assert.equal(result.skipped,1);assert.equal(result.merged[id].updatedAt,local.updatedAt)});
test('backup merge adds a new race and migration timestamps',async()=>{const c=await loadCore(),incoming=race(),id='2026-08-30|船橋|4';incoming.updatedAt='2026-08-30T09:00:00Z';incoming.predictionSnapshot.createdAt='2026-08-30T08:00:00Z';incoming.resultSnapshot.fetchedAt='2026-08-30T09:00:00Z';const result=c.mergeResearchBackup({format:'CHASS_KEIBA_RESEARCH_BACKUP',schemaVersion:1,races:{[id]:incoming}},{});assert.equal(result.imported,1);assert.equal(result.merged[id].predictionCreatedAt,'2026-08-30T08:00:00Z');assert.equal(result.merged[id].resultAcquiredAt,'2026-08-30T09:00:00Z')});

class FakeD1{
 constructor(){this.races=new Map();this.predictions=new Set();this.results=new Set();this.resultData=new Map();this.failHealth=false;this.dataWrites=0;this.sqlCount=0}
 prepare(sql){const db=this,statement={sql,args:[],bind(...args){this.args=args;return this},async first(){db.sqlCount++;if(db.failHealth)throw new Error('D1 unavailable');if(/^SELECT 1/i.test(sql))return {ok:1};if(/FROM races WHERE race_id=\?/i.test(sql))return db.races.get(`${this.args[0]}|${this.args[1]}`)||null;return null},async all(){db.sqlCount++;if(/FROM predictions/i.test(sql)){const groups=new Map();for(const key of db.predictions){const parts=key.split('|');parts.pop();const model_version=parts.pop(),race_id=parts.join('|'),group=`${race_id}\u0000${model_version}`;groups.set(group,(groups.get(group)||0)+1)}return {results:[...groups].map(([key,horse_count])=>{const [race_id,model_version]=key.split('\u0000');return {race_id,model_version,horse_count}})}}if(/FROM results/i.test(sql))return {results:[...db.resultData.values()]};if(/FROM races/i.test(sql))return {results:[...db.races.values()]};return {results:[]}}};return statement}
 async batch(statements){for(const s of statements){this.sqlCount++;if(/^INSERT INTO races/i.test(s.sql)){this.dataWrites++;const key=`${s.args[0]}|${s.args[1]}`;this.races.set(key,{race_id:s.args[0],model_version:s.args[1],race_json:s.args[2],prediction_json:s.args[3],market_json:s.args[4],final_json:s.args[5],result_json:s.args[6],validation_json:s.args[7],prediction_created_at:s.args[8],result_acquired_at:s.args[9],status:s.args[10],updated_at:s.args[11],prediction:s.args[3],result:s.args[6]})}else if(/^UPDATE races SET result_json=\?,validation_json/i.test(s.sql)){this.dataWrites++;const row=this.races.get(`${s.args[5]}|${s.args[6]}`);Object.assign(row,{result_json:s.args[0],result:s.args[0],validation_json:s.args[1],result_acquired_at:s.args[2],status:s.args[3],updated_at:s.args[4]})}else if(/^UPDATE races SET result_json/i.test(s.sql)){this.dataWrites++;const row=this.races.get(`${s.args[4]}|${s.args[5]}`);Object.assign(row,{result_json:s.args[0],result:s.args[0],result_acquired_at:s.args[1],status:s.args[2],updated_at:s.args[3]})}else if(/^UPDATE races SET validation_json/i.test(s.sql)){this.dataWrites++;const row=this.races.get(`${s.args[3]}|${s.args[4]}`);Object.assign(row,{validation_json:s.args[0],status:s.args[1],updated_at:s.args[2]})}else if(/^INSERT OR IGNORE INTO predictions/i.test(s.sql)){const key=`${s.args[0]}|${s.args[1]}|${s.args[2]}`;if(!this.predictions.has(key)){this.dataWrites++;this.predictions.add(key)}}else if(/^INSERT INTO results/i.test(s.sql)){this.dataWrites++;const key=`${s.args[0]}|${s.args[1]}`;this.results.add(key);this.resultData.set(key,{race_id:s.args[0],horse_no:s.args[1],finish:s.args[2],actual_time:s.args[3],final_3f:s.args[4],passing_order:s.args[5],result_acquired_at:s.args[6],result_json:s.args[7]})}}return statements.map(()=>({success:true}))}
}
test('D1 binding uses the Cloudflare DB binding',()=>{const db=new FakeD1();assert.equal(getResearchDb({DB:db}),db);assert.equal(getResearchDb({'chass-keiba-lab-db':db}),null)});
test('Wrangler config declares the production D1 DB binding',async()=>{const source=await readFile(new URL('./wrangler.jsonc',import.meta.url),'utf8'),config=JSON.parse(source),binding=config.d1_databases?.find(x=>x.binding==='DB');assert.ok(binding);assert.equal(binding.database_name,'chass-keiba-research-db');assert.match(binding.database_id,/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)});
test('D1 schema defines races predictions and results without deletes',async()=>{const sql=await readFile(new URL('./d1-schema.sql',import.meta.url),'utf8');for(const table of ['races','predictions','results'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.doesNotMatch(sql,/\bDELETE\b/i)});
test('DB health reports connected and missing binding safely',async()=>{const db=new FakeD1(),ok=await worker.fetch(new Request('https://example.com/api/db/health'),{DB:db}),missing=await worker.fetch(new Request('https://example.com/api/db/health'),{});assert.equal((await ok.json()).database,'connected');assert.equal(missing.status,503);assert.equal((await missing.json()).error,'d1_binding_unavailable')});
test('DB health classifies SELECT failure as d1_query_failed',async()=>{const db=new FakeD1();db.failHealth=true;const response=await worker.fetch(new Request('https://example.com/api/db/health'),{DB:db});assert.equal(response.status,503);assert.equal((await response.json()).error,'d1_query_failed')});
test('D1 schema initialization failure is classified',async()=>{const db=new FakeD1();db.batch=async()=>{throw new Error('schema denied')};await assert.rejects(()=>ensureD1Schema(db),error=>error.code==='d1_schema_error')});
test('D1 row mapping stores required prediction and result fields',()=>{const r=race(),rows=d1RecordRows('2026-08-30|船橋|4',r),p=rows.predictions[0],x=rows.results[0];assert.equal(p.aiWinRate,45);assert.equal(p.aiPlaceRate,70);assert.equal(p.predictedTime,'1:40.0');assert.equal(x.actualTime,'1:42.0');assert.equal(x.final3F,38)});
test('D1 duplicate sync does not duplicate predictions or results',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);await saveD1Record(db,id,r);assert.equal(db.races.size,1);assert.equal(db.predictions.size,4);assert.equal(db.results.size,4)});
test('identical second D1 sync executes zero data writes',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';const first=await saveD1Record(db,id,r),before=db.dataWrites,second=await saveD1Record(db,id,JSON.parse(JSON.stringify(r)));assert.equal(first.status,'created');assert.equal(second.status,'unchanged');assert.equal(second.written,false);assert.equal(db.dataWrites,before)});
test('result-only change updates result without touching prediction rows',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);const predictions=db.predictions.size,before=db.dataWrites,next=JSON.parse(JSON.stringify(r));next.resultSnapshot.finishOrder=[1,2,3,4];next.updatedAt='2026-08-30T11:00:00Z';const result=await saveD1Record(db,id,next);assert.equal(result.status,'updated');assert.equal(result.predictions,0);assert.equal(db.predictions.size,predictions);assert.ok(db.dataWrites>before)});
test('validation-only change does not rewrite predictions or results',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';r.validationSnapshot=null;r.validationCompleted=false;await saveD1Record(db,id,r);const predictions=db.predictions.size,results=db.results.size,next=JSON.parse(JSON.stringify(r));next.validationSnapshot={schemaVersion:3,failures:[]};next.validationCompleted=true;next.updatedAt='2026-08-30T12:00:00Z';const result=await saveD1Record(db,id,next);assert.equal(result.status,'updated');assert.equal(result.predictions,0);assert.equal(result.results,0);assert.equal(db.predictions.size,predictions);assert.equal(db.results.size,results)});
test('result acquisition never changes prediction fingerprint',()=>{const r=race(),id='2026-08-30|船橋|4',before=d1SyncDescriptor(id,r).predictionFingerprint,next=JSON.parse(JSON.stringify(r));next.resultSnapshot.finishOrder=[1,2,3,4];assert.equal(d1SyncDescriptor(id,next).predictionFingerprint,before)});
test('stable fallback updatedAt does not change between descriptors',()=>{const r=race(),id='2026-08-30|船橋|4';delete r.updatedAt;r.predictionSnapshot.createdAt='2026-08-30T08:00:00Z';assert.equal(d1SyncDescriptor(id,r).updatedAt,d1SyncDescriptor(id,JSON.parse(JSON.stringify(r))).updatedAt)});
test('different model versions create separate immutable race snapshots',async()=>{const db=new FakeD1(),a=race(),b=race(),id='2026-08-30|船橋|4';a.predictionSnapshot.modelVersion='9.9.5';b.predictionSnapshot.modelVersion='9.9.6';await saveD1Record(db,id,a);await saveD1Record(db,id,b);assert.equal(db.races.size,2)});
test('manifest exposes fingerprints without snapshot bodies',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);const records=await readD1Manifest(db),serialized=JSON.stringify(records);assert.equal(records.length,1);assert.ok(records[0].predictionFingerprint);assert.doesNotMatch(serialized,/predictionSnapshot|prediction_json|horses/)});
test('manifest API returns only lightweight differential records',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);const response=await worker.fetch(new Request('https://example.com/api/db/manifest'),{DB:db}),body=await response.json();assert.equal(body.ok,true);assert.equal(body.records.length,1);assert.equal('predictionSnapshot' in body.records[0],false)});
test('D1 research dataset reconstructs results missing from races JSON',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);const row=db.races.get(`${id}|9.9.3`);row.result_json=null;row.result=null;row.status='prediction_saved';const dataset=await readD1ResearchDataset(db),item=dataset.records[0];assert.equal(dataset.counts.d1PredictionSaved,1);assert.equal(dataset.counts.d1ResultFetched,1);assert.equal(dataset.counts.validationEligible,1);assert.equal(item.reconstructedResult,true);assert.deepEqual(item.record.resultSnapshot.finishOrder,[2,3,4,1])});
test('D1 research audit separates result-missing from validation exclusions',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';r.resultSnapshot=null;r.validationSnapshot=null;r.validationCompleted=false;await saveD1Record(db,id,r);const dataset=await readD1ResearchDataset(db);assert.equal(dataset.counts.resultMissing,1);assert.equal(dataset.counts.validationEligible,0);assert.equal(dataset.counts.excluded,0);assert.equal(dataset.exclusions.length,0);assert.equal(dataset.missingResults[0].reason,'RESULT_MISSING');assert.equal(dataset.counts.consistency.predictionBalance,true);assert.equal(dataset.counts.consistency.resultBalance,true);assert.equal(db.races.size,1)});
test('cloud restore fills missing result when immutable prediction is identical',async()=>{const c=await loadCore(),local=race(),cloud=race(),before=JSON.stringify(local.predictionSnapshot);local.resultSnapshot=null;local.validationSnapshot=null;local.validationCompleted=false;const merged=c.mergeCloudResearchRecord(local,cloud,{eligible:true});assert.equal(JSON.stringify(merged.predictionSnapshot),before);assert.deepEqual(merged.resultSnapshot.finishOrder,[2,3,4,1]);assert.equal(merged.validated,true)});
test('cloud restore never overwrites a conflicting prediction snapshot',async()=>{const c=await loadCore(),local=race(),cloud=race(),before=JSON.stringify(local.predictionSnapshot);cloud.predictionSnapshot.horses[0].win=1;const merged=c.mergeCloudResearchRecord(local,cloud,{eligible:true});assert.equal(JSON.stringify(merged.predictionSnapshot),before);assert.equal(merged.cloudConflict,true);assert.equal(merged.cloudConflictReason,'DUPLICATE_OR_CONFLICT')});
test('D1 research API is read-only and reports result-missing separately',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';r.resultSnapshot=null;r.validationCompleted=false;await saveD1Record(db,id,r);const writes=db.dataWrites,response=await worker.fetch(new Request('https://example.com/api/db/research'),{DB:db}),body=await response.json();assert.equal(body.ok,true);assert.equal(body.missingResults[0].raceId,id);assert.equal(body.exclusions.length,0);assert.equal(db.dataWrites,writes)});
test('manual differential sync sends no snapshot body when manifest matches',async()=>{const id='2026-08-30|船橋|4',r=race();let syncPosts=0,descriptor;const c=await loadCore(async(url,options={})=>{if(String(url).endsWith('/api/db/manifest'))return new Response(JSON.stringify({ok:true,records:[descriptor]}),{headers:{'content-type':'application/json'}});if(String(url).endsWith('/api/db/sync')){syncPosts++;return new Response(JSON.stringify({ok:true,synced:0,created:0,updated:0,unchanged:1,records:[]}),{headers:{'content-type':'application/json'}})}throw new Error(`unexpected ${url}`)});c.getRaceCache()[id]=r;descriptor=c.cloudDescriptor(id,r);const result=await c.syncAllResearchToCloud();assert.equal(result.target,0);assert.equal(result.unchanged,1);assert.equal(syncPosts,0)});
test('no research DELETE API is exposed',async()=>{const db=new FakeD1(),response=await worker.fetch(new Request('https://example.com/api/db/races',{method:'DELETE'}),{DB:db});assert.equal(response.status,404)});
test('D1 result update never overwrites immutable prediction snapshot',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);const key=`${id}|9.9.3`,before=db.races.get(key).prediction;r.predictionSnapshot.horses[0].win=1;r.resultSnapshot.finishOrder=[1,2,3,4];await saveD1Record(db,id,r);assert.equal(db.races.get(key).prediction,before);assert.equal(JSON.parse(before).horses[0].win,45)});
test('stale prediction-only sync cannot clear an existing cloud result',async()=>{const db=new FakeD1(),r=race(),id='2026-08-30|船橋|4';await saveD1Record(db,id,r);const key=`${id}|9.9.3`,before=db.races.get(key).result_json,writes=db.dataWrites,stale=race();stale.resultSnapshot=null;const response=await saveD1Record(db,id,stale);assert.equal(response.status,'unchanged');assert.equal(db.races.get(key).result_json,before);assert.equal(db.dataWrites,writes)});
test('D1 failure keeps frontend in local fallback mode',async()=>{const c=await loadCore(async()=>new Response(JSON.stringify({ok:false,error:'d1_binding_unavailable'}),{status:503,headers:{'content-type':'application/json'}}));assert.equal(await c.initCloudResearch(),false);assert.equal(c.getCloudState().source,'local')});


test('NAR resilience exposes endpoint diagnostics on failure',async()=>{const fetcher=async()=>{const e=new TypeError('fetch failed');e.code='network_error';throw e};await assert.rejects(()=>fetchNarResultResilient('https://example.test/primary','https://example.test/fallback',{fetcher,sleeper:async()=>{}}),e=>Array.isArray(e.diagnostics)&&e.diagnostics.length===3&&e.fallbackTried===true)});

test('result fetch success cannot be downgraded by optional odds/meta enrichment',async()=>{const worker=await readFile(new URL('./worker.js',import.meta.url),'utf8');assert.match(worker,/Lock official-result success before optional enrichment/);assert.match(worker,/partialSuccess:optionalErrors\.length>0/);assert.match(worker,/odds_fetch_failed/);const app=await readFile(new URL('./app.js',import.meta.url),'utf8');assert.match(app,/resultFetchSuccess:true/);assert.match(app,/primarySyncAudit/);assert.match(app,/recoveryAudit/);assert.match(app,/postFetchAudit/)});
test('generic unknown_error fallback is not used in result acquisition',async()=>{for(const file of ['./worker.js','./app.js','./server.mjs']){const src=await readFile(new URL(file,import.meta.url),'utf8');assert.doesNotMatch(src,/unknown_error/)}});
