import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {horseStatusFromText,parseRaceCard,parseTanFuku,parseResult,d1RecordRows,mapChassRace} from '../worker.js';

async function core(){const source=await readFile(new URL('../app.js',import.meta.url),'utf8'),window={__CHASS_TEST__:true},document={getElementById(){return {value:'',addEventListener(){},classList:{toggle(){}}}},localStorage:{getItem(){return null},setItem(){}},console,setTimeout,clearTimeout,setInterval,clearInterval,Date,Math,JSON,Map,Set,URL,Blob,TextEncoder,structuredClone};const context={window,document,...window};vm.createContext(context);vm.runInContext(source,context,{filename:'app.js'});return window.CHASS_TEST}
function horse(no,win,place,overall,style='先行',pop=no){return {horseNo:no,horseName:`馬${no}`,win,place,overall,runningStyle:style,popularity:pop,odds:2+no,predictedTime:`1:2${no}.0`,predictedTimeType:'実績',dataConfidence:70,raw:{highest:90-no,avg5:80-no,distance:75,course:75,recent:[80,81]},scores:{timeIndex:70-no,distanceFit:70,courseFit:70,weight:50},features:{distanceFit:70,courseFit:70,recentFormScore:70,consistencyScore:70},predictionAxes:{paceFitScore:60,placeStabilityScore:65,speedCeilingScore:65,distanceChangeFit:60,conditionProgressScore:60,evidenceCount:6},valueMark:no===4?'💎':'',warningMark:'',abilityMark:no===1?'◎':'',finalMark:no===1?'◎':no===2?'○':no===3?'▲':''}}
function record(){const horses=[horse(1,32,60,92,'逃げ',1),horse(2,24,55,86,'先行',2),horse(3,18,48,80,'差し',3),horse(4,14,42,74,'追込',8),horse(5,12,38,70,'先行',5)];return {race:{raceDate:'2026-08-31',track:'大井',raceNo:8,pace:'標準',chaos:55,oddsType:'実オッズ'},predictionSnapshot:{modelVersion:'9.9.28',createdAt:'2026-08-31T09:00:00.000Z',race:{raceDate:'2026-08-31',track:'大井',raceNo:8,pace:'標準'},horses:structuredClone(horses),volatility:{volatilityIndex:62},axisModel:{raceConfidence:68}},marketSnapshot:{horses:horses.map(x=>({horseNo:x.horseNo,odds:x.odds,popularity:x.popularity,ev:x.odds*x.win,valueMark:x.valueMark}))},finalSnapshot:{top3:[{horseNo:1,mark:'◎'},{horseNo:2,mark:'○'},{horseNo:3,mark:'▲'}],ranking:horses.map((x,i)=>({horseNo:x.horseNo,mark:x.finalMark,rank:i+1}))},horses:structuredClone(horses)}}

test('status vocabulary maps official scratch labels',()=>{assert.equal(horseStatusFromText('出走取消'),'scratched');assert.equal(horseStatusFromText('競走除外'),'excluded');assert.equal(horseStatusFromText('出走取止'),'withdrawn')});
test('scratch changes runner status only and Original Snapshot stays byte-stable',async()=>{const c=await core(),r=record(),before=c.snapshotFingerprint(r.predictionSnapshot);c.applyScratchStatuses(r,[{horseNo:3,statusText:'出走取消'}],'2026-08-31T10:00:00.000Z');assert.equal(c.snapshotFingerprint(r.predictionSnapshot),before);assert.equal(r.liveAdjustedPrediction,undefined);assert.equal(r.horses.find(x=>x.horseNo===3).runnerStatus,'scratched');assert.equal(r.horses.find(x=>x.horseNo===3).eligible,false)});
test('other horses keep win TOP3 mark EV longshot and warning after scratch',async()=>{const c=await core(),r=record(),before=structuredClone(r.horses);c.applyScratchStatuses(r,[{horseNo:4,horseStatus:'scratched'}]);for(const h of r.horses.filter(x=>x.horseNo!==4)){const old=before.find(x=>x.horseNo===h.horseNo);assert.equal(h.win,old.win);assert.equal(h.place,old.place);assert.equal(h.finalMark,old.finalMark);assert.equal(h.ev,old.ev);assert.equal(h.valueMark,old.valueMark);assert.equal(h.warningMark,old.warningMark)}});
test('favorite scratch does not reselect marks or recalculate pace',async()=>{const c=await core(),r=record(),final=c.snapshotFingerprint(r.finalSnapshot),pace=r.race.pace;c.applyScratchStatuses(r,[{horseNo:1,horseStatus:'scratched'}]);assert.equal(c.snapshotFingerprint(r.finalSnapshot),final);assert.equal(r.race.pace,pace);assert.equal(r.finalSnapshot.top3[0].horseNo,1)});
test('odds missing alone never creates scratch status',async()=>{const c=await core(),r=record();c.applyScratchStatuses(r,[{horseNo:4,odds:null,popularity:null}]);assert.equal(r.scratchAudit,undefined);assert.equal(r.horses.find(x=>x.horseNo===4).eligible,undefined)});
test('official active row can recover a stale excluded status',async()=>{const c=await core(),r=record();c.applyScratchStatuses(r,[{horseNo:4,statusText:'競走除外'}],'2026-09-08T10:00:00.000Z',{source:'NAR_RACE_CARD'});c.applyScratchStatuses(r,[{horseNo:4,horseStatus:'active'}],'2026-09-08T10:01:00.000Z',{source:'NAR_RACE_CARD',authoritativeActive:true});const h=r.horses.find(x=>x.horseNo===4);assert.equal(h.runnerStatus,'active');assert.equal(h.eligible,true);assert.equal(r.scratchAudit.inactiveHorseNos.length,0)});
test('confirmed result participation overrides false exclusion without changing prediction',async()=>{const c=await core(),r=record(),before=c.snapshotFingerprint(r.predictionSnapshot);c.applyScratchStatuses(r,[{horseNo:4,statusText:'競走除外'}]);r.resultSnapshot={finishOrder:[2,4,5],horses:[{horseNo:4,position:2,time:'2:20.1'}]};c.applyScratchStatuses(r,r.resultSnapshot.horses,'2026-09-08T12:00:00.000Z',{source:'NAR_RESULT',resultAuthority:true});assert.equal(r.scratchAudit.statusByHorse[4],'active');assert.equal(r.scratchAudit.reconciliations.at(-1).code,'STATUS_RECONCILED_FROM_RESULT');assert.equal(c.buildScratchValidation(r),null);assert.equal(c.snapshotFingerprint(r.predictionSnapshot),before)});
test('unknown and missing market data never gray a runner',async()=>{const c=await core(),r=record();c.applyScratchStatuses(r,[{horseNo:3,horseStatus:'unknown',odds:null}],'2026-09-08T10:00:00.000Z',{source:'NAR_ODDS'});assert.notEqual(r.horses.find(x=>x.horseNo===3).eligible,false);assert.equal(r.scratchAudit,undefined)});
test('scratch validation excludes inactive runner from Original denominator',async()=>{const c=await core(),r=record();c.applyScratchStatuses(r,[{horseNo:1,statusText:'出走取消'}]);r.resultSnapshot={finishOrder:[2,4,5]};const v=c.buildScratchValidation(r);assert.equal(v.officialBasis,'original_snapshot');assert.equal(v.mode,'status_only');assert.equal(v.originalDenominator,2);assert.equal(v.scratchExcludedHorseNos.join(','),'1')});
test('D1 preserves legacy Live data while new status audit stays separate',()=>{const r=record(),original=JSON.stringify(r.predictionSnapshot);r.liveAdjustedPrediction={excludedHorseNos:[1],legacy:true};r.scratchAudit={schemaVersion:2,mode:'status_only',statusByHorse:{1:'scratched'}};const rows=d1RecordRows('2026-08-31|大井|8',r),race=JSON.parse(rows.race.raceJson);assert.equal(rows.race.predictionJson,original);assert.equal(race.liveAdjustedPrediction.legacy,true);assert.equal(race.scratchAudit.mode,'status_only')});
test('D1 and AI bridge reconcile a result finisher from excluded to active',()=>{const r=record();r.scratchAudit={schemaVersion:2,mode:'status_only',statusByHorse:{4:'excluded'}};r.resultSnapshot={fetchedAt:'2026-09-08T12:00:00.000Z',finishOrder:[2,4,5],horses:[{horseNo:4,position:2,time:'2:20.1'}]};const rows=d1RecordRows('2026-09-08|川崎|12',r),stored=JSON.parse(rows.race.raceJson),mapped=mapChassRace({raceId:'2026-09-08|川崎|12',record:r});assert.equal(stored.scratchAudit.statusByHorse[4],'active');assert.equal(mapped.original.horses.find(x=>x.horseNo===4).status,'active');assert.equal(mapped.scratch.scratchCount,0)});
test('RaceCard and odds parsers retain cancelled runner instead of dropping it',()=>{const card='<table><tr><td>1</td><td>1</td><td>テストホース</td><td>出走取消</td></tr></table>',odds='<table><tr><td>1</td><td>1</td><td>テストホース</td><td>取消</td></tr></table>';const c=parseRaceCard(card),o=parseTanFuku(odds);assert.equal(c[0].horseStatus,'scratched');assert.equal(o[0].horseStatus,'scratched');assert.equal(o[0].odds,null)});
test('result parser exposes exclusion status',()=>{const html='<table><tr><th>着順</th><th>馬番</th><th>馬名</th><th>タイム</th></tr><tr><td>除外</td><td>3</td><td>テストホース</td><td></td></tr></table>';const p=parseResult(html);assert.equal(p.results[0].horseStatus,'excluded');assert.equal(p.results[0].eligible,false)});
