import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {horseStatusFromText,parseRaceCard,parseTanFuku,parseResult,d1RecordRows} from '../worker.js';

async function core(){const source=await readFile(new URL('../app.js',import.meta.url),'utf8'),window={__CHASS_TEST__:true},document={getElementById(){return {value:'',addEventListener(){},classList:{toggle(){}}}},localStorage:{getItem(){return null},setItem(){}},console,setTimeout,clearTimeout,setInterval,clearInterval,Date,Math,JSON,Map,Set,URL,Blob,TextEncoder,structuredClone};const context={window,document,...window};vm.createContext(context);vm.runInContext(source,context,{filename:'app.js'});return window.CHASS_TEST}
function horse(no,win,place,overall,style='先行',pop=no){return {horseNo:no,horseName:`馬${no}`,win,place,overall,runningStyle:style,popularity:pop,odds:2+no,predictedTime:`1:2${no}.0`,predictedTimeType:'実績',dataConfidence:70,raw:{highest:90-no,avg5:80-no,distance:75,course:75,recent:[80,81]},scores:{timeIndex:70-no,distanceFit:70,courseFit:70,weight:50},features:{distanceFit:70,courseFit:70,recentFormScore:70,consistencyScore:70},predictionAxes:{paceFitScore:60,placeStabilityScore:65,speedCeilingScore:65,distanceChangeFit:60,conditionProgressScore:60,evidenceCount:6},valueMark:no===4?'💎':'',warningMark:'',abilityMark:no===1?'◎':'',finalMark:no===1?'◎':no===2?'○':no===3?'▲':''}}
function record(){const horses=[horse(1,32,60,92,'逃げ',1),horse(2,24,55,86,'先行',2),horse(3,18,48,80,'差し',3),horse(4,14,42,74,'追込',8),horse(5,12,38,70,'先行',5)];return {race:{raceDate:'2026-08-31',track:'大井',raceNo:8,pace:'標準',chaos:55,oddsType:'実オッズ'},predictionSnapshot:{modelVersion:'9.9.28',createdAt:'2026-08-31T09:00:00.000Z',race:{raceDate:'2026-08-31',track:'大井',raceNo:8,pace:'標準'},horses:structuredClone(horses),volatility:{volatilityIndex:62},axisModel:{raceConfidence:68}},marketSnapshot:{horses:horses.map(x=>({horseNo:x.horseNo,odds:x.odds,popularity:x.popularity,ev:x.odds*x.win,valueMark:x.valueMark}))},finalSnapshot:{top3:[{horseNo:1,mark:'◎'},{horseNo:2,mark:'○'},{horseNo:3,mark:'▲'}],ranking:horses.map((x,i)=>({horseNo:x.horseNo,mark:x.finalMark,rank:i+1}))},horses:structuredClone(horses)}}

test('status vocabulary maps official scratch labels',()=>{assert.equal(horseStatusFromText('出走取消'),'scratched');assert.equal(horseStatusFromText('競走除外'),'excluded');assert.equal(horseStatusFromText('出走取止'),'withdrawn')});
test('Original Snapshot is byte-stable while Live excludes scratched horse',async()=>{const c=await core(),r=record(),before=c.snapshotFingerprint(r.predictionSnapshot);c.applyScratchStatuses(r,[{horseNo:3,statusText:'出走取消'}],'2026-08-31T10:00:00.000Z',[]);assert.equal(c.snapshotFingerprint(r.predictionSnapshot),before);assert.deepEqual(r.liveAdjustedPrediction.excludedHorseNos,[3]);assert.equal(r.liveAdjustedPrediction.horses.find(x=>x.horseNo===3).eligible,false)});
test('live win probabilities renormalize to 100 and market is disabled for scratch',async()=>{const c=await core(),r=record();c.applyScratchStatuses(r,[{horseNo:4,horseStatus:'scratched'}]);const active=r.liveAdjustedPrediction.horses.filter(c.isEligibleHorse);assert.ok(Math.abs(active.reduce((s,x)=>s+x.win,0)-100)<.03);const removed=r.liveAdjustedPrediction.horses.find(x=>x.horseNo===4);assert.equal(removed.odds,null);assert.equal(removed.ev,null)});
test('favorite scratch is high impact and live mark is reselected',async()=>{const c=await core(),r=record();c.applyScratchStatuses(r,[{horseNo:1,horseStatus:'scratched'}]);assert.ok(r.liveAdjustedPrediction.scratchImpactScore>=40);assert.equal(r.finalSnapshot.top3[0].horseNo,1);assert.notEqual(r.liveAdjustedPrediction.finalSnapshot.top3[0].horseNo,1)});
test('only front runner scratch recalculates pace',async()=>{const c=await core(),r=record();c.applyScratchStatuses(r,[{horseNo:1,statusText:'出走取消'}]);assert.equal(r.liveAdjustedPrediction.livePace,'スロー')});
test('scratch validation excludes inactive original pick denominator and compares Live',async()=>{const c=await core(),r=record();c.applyScratchStatuses(r,[{horseNo:1,statusText:'出走取消'}]);r.resultSnapshot={finishOrder:[2,4,5]};const v=c.buildScratchValidation(r);assert.equal(v.officialBasis,'original_snapshot');assert.equal(v.originalDenominator,2);assert.equal(v.liveDenominator,3)});
test('D1 keeps original prediction_json and stores Live only in race_json',()=>{const r=record(),original=JSON.stringify(r.predictionSnapshot);r.liveAdjustedPrediction={excludedHorseNos:[1]};r.scratchAudit={statusByHorse:{1:'scratched'}};const rows=d1RecordRows('2026-08-31|大井|8',r),race=JSON.parse(rows.race.raceJson);assert.equal(rows.race.predictionJson,original);assert.deepEqual(race.liveAdjustedPrediction.excludedHorseNos,[1]);assert.equal(race.scratchAudit.statusByHorse[1],'scratched')});
test('RaceCard and odds parsers retain cancelled runner instead of dropping it',()=>{const card='<table><tr><td>1</td><td>1</td><td>テストホース</td><td>出走取消</td></tr></table>',odds='<table><tr><td>1</td><td>1</td><td>テストホース</td><td>取消</td></tr></table>';const c=parseRaceCard(card),o=parseTanFuku(odds);assert.equal(c[0].horseStatus,'scratched');assert.equal(o[0].horseStatus,'scratched');assert.equal(o[0].odds,null)});
test('result parser exposes exclusion status',()=>{const html='<table><tr><th>着順</th><th>馬番</th><th>馬名</th><th>タイム</th></tr><tr><td>除外</td><td>3</td><td>テストホース</td><td></td></tr></table>';const p=parseResult(html);assert.equal(p.results[0].horseStatus,'excluded');assert.equal(p.results[0].eligible,false)});
