import test from 'node:test';
import assert from 'node:assert/strict';
import {SIMILARITY_VERSION,SIMILARITY_WEIGHTS,extractSimilarityFeatures,similarityScore,analyzeHistoricalSimilarity,walkForwardSimilarity} from '../similarity-intelligence.mjs';

const sum=object=>Object.values(object).reduce((a,b)=>a+b,0);
function iso(day,hour=1){return `2026-07-${String(day).padStart(2,'0')}T${String(hour).padStart(2,'0')}:00:00.000Z`}
function horse(no,{pop=no,style=no===1?'逃げ':no<=3?'先行':no<=6?'差し':'追込',time=true}={}){return {horseNo:no,horseName:`馬${no}`,abilityScore:100-no*3,overall:98-no*2,win:Math.max(2,25-no*2),place:Math.max(8,60-no*4),predictedTime:time?`1:${String(37+no/3).padStart(4,'0')}`:'',popularity:pop,odds:1.8+pop*1.7,marketGapScore:pop>=7?55:10,runningStyle:style,valueMark:pop>=7?'💎':'',valueType:pop>=7?'相手穴':'',warningMark:pop===1?'⚠️':'',predictionAxes:{paceFitScore:no===1?42:72,placeStabilityScore:80-no,predictionConsensus:no===1?44:75}}}
function item(day,{track='大井',distance=1600,field=12,surface='ダート',condition='良',raceClass='C2',pace='標準',finish=[7,2,1],prediction=iso(day,1),result=iso(day,3),raceId=`2026-07-${String(day).padStart(2,'0')}|${track}|8`,live=false,missing=false}={}){
 const horses=Array.from({length:field},(_,i)=>horse(i+1,{time:!(missing&&i===field-1)})),record={race:{raceDate:prediction.slice(0,10),track,raceNo:8,distance,surface,trackCondition:condition,raceClass,pace},predictionSnapshot:{modelVersion:'9.9.31',createdAt:prediction,race:{track,distance,surface,trackCondition:condition,raceClass,pace},volatility:{volatilityIndex:68},axisModel:{raceConfidence:57},horses},marketSnapshot:{acquiredAt:prediction,horses:horses.map(h=>({horseNo:h.horseNo,popularity:h.popularity,odds:h.odds,marketGapScore:h.marketGapScore,valueMark:h.valueMark,valueType:h.valueType,warningMark:h.warningMark}))},finalSnapshot:{top3:[{horseNo:1},{horseNo:2},{horseNo:3}]},resultSnapshot:result?{fetchedAt:result,finishOrder:finish,horses:finish.map((horseNo,index)=>({horseNo,position:index+1}))}:null,predictionCreatedAt:prediction,resultAcquiredAt:result,validationCompleted:!!result};
 if(live){record.race.liveAdjustedPrediction={createdAt:prediction,adjustedFromModelVersion:'9.9.31',excludedHorseNos:[12],horses:horses.slice(0,-1).map(h=>({...h,horseStatus:'active'})),volatility:{volatilityIndex:61},raceConfidence:62}}
 return {raceId,record}
}

test('similarity v1 weights total 100 and remain shadow-only',()=>{assert.equal(SIMILARITY_VERSION,'similarity_v1');assert.equal(sum(SIMILARITY_WEIGHTS),100)});
test('same track and distance outrank ±200m and another track',()=>{const target=extractSimilarityFeatures(item(31)),same=extractSimilarityFeatures(item(30)),near=extractSimilarityFeatures(item(29,{distance:1800})),other=extractSimilarityFeatures(item(28,{track:'園田'}));const a=similarityScore(target,same).score,b=similarityScore(target,near).score,c=similarityScore(target,other).score;assert.ok(a>b);assert.ok(b>c);assert.equal(similarityScore(target,extractSimilarityFeatures(item(27,{distance:2200}))).hardExcluded,'distance_out_of_range')});
test('surface mismatch is a hard exclusion',()=>{const score=similarityScore(extractSimilarityFeatures(item(31)),extractSimilarityFeatures(item(30,{surface:'芝'})));assert.equal(score.score,0);assert.equal(score.hardExcluded,'surface_mismatch')});
test('small field and different pace structure reduce similarity',()=>{const target=extractSimilarityFeatures(item(31)),close=similarityScore(target,extractSimilarityFeatures(item(30,{field:13}))).score,small=similarityScore(target,extractSimilarityFeatures(item(29,{field:6,pace:'ハイ'}))).score;assert.ok(close>small)});
test('future result and result acquired after prediction are excluded',()=>{const target=item(31),past=item(20),future=item(30,{prediction:'2026-09-01T01:00:00.000Z',result:'2026-09-01T03:00:00.000Z'}),late=item(29,{result:'2026-09-02T03:00:00.000Z'}),analysis=analyzeHistoricalSimilarity(target,[past,future,late]);assert.equal(analysis.similarRaceCount,1);assert.equal(analysis.topSimilarRaces[0].raceId,past.raceId)});
test('Historical Collector backtest predictions are excluded from success and failure learning',()=>{const target=item(31),realtime=item(20),backtest=item(19);backtest.record.predictionSnapshot.historicalResearch=true;backtest.record.predictionSnapshot.predictionKind='backtest_prediction';backtest.record.race.predictionKind='backtest_prediction';const analysis=analyzeHistoricalSimilarity(target,[realtime,backtest]);assert.equal(analysis.similarRaceCount,1);assert.equal(analysis.topSimilarRaces[0].raceId,realtime.raceId);const report=walkForwardSimilarity([realtime,backtest]);assert.equal(report.targetCount,1)});
test('prediction snapshot is used and post-result mutation cannot change features',()=>{const race=item(20),before=extractSimilarityFeatures(race);race.record.resultSnapshot.trackCondition='不良';race.record.horses=[horse(1,{pop:12})];const after=extractSimilarityFeatures(race);assert.equal(after.trackCondition,before.trackCondition);assert.deepEqual(after.winVector,before.winVector)});
test('missing TIME and odds are omitted without crashing',()=>{const target=item(31,{missing:true});target.record.marketSnapshot={acquiredAt:target.record.predictionCreatedAt,horses:[]};const histories=Array.from({length:20},(_,i)=>item(i+1,{missing:i%2===0})),analysis=analyzeHistoricalSimilarity(target,histories);assert.equal(analysis.available,true);assert.ok(analysis.dataCoverage>0);assert.ok(Number.isFinite(analysis.averageSimilarityScore))});
test('small sample lowers confidence and 50 histories raise it',()=>{const target=item(31),small=analyzeHistoricalSimilarity(target,Array.from({length:5},(_,i)=>item(i+1))),large=analyzeHistoricalSimilarity(target,Array.from({length:30},(_,i)=>item(i+1)));assert.ok(small.similarityConfidence<large.similarityConfidence);assert.equal(small.confidenceLabel,'低');assert.ok(large.similarRaceCount>=20)});
test('success and failure patterns require at least ten horse samples',()=>{const target=item(31),analysis=analyzeHistoricalSimilarity(target,Array.from({length:25},(_,i)=>item(i+1)));for(const row of [...analysis.successPatterns,...analysis.failurePatterns])assert.ok(row.sampleCount>=10);assert.ok(analysis.successPatterns.some(x=>x.pattern==='high_place_low_market'));assert.ok(analysis.failurePatterns.some(x=>x.pattern==='top_ability_pace_mismatch'))});
test('horse historical support is explanatory and never changes target probabilities',()=>{const target=item(31),before=structuredClone(target.record.predictionSnapshot.horses),analysis=analyzeHistoricalSimilarity(target,Array.from({length:25},(_,i)=>item(i+1)));assert.equal(analysis.horseSupport.length,12);assert.ok(['support','neutral','conflict'].includes(analysis.horseSupport[0].classification));assert.deepEqual(target.record.predictionSnapshot.horses,before);assert.equal(analysis.adopted,false)});
test('Original and Live analyses remain separate',()=>{const target=item(31,{live:true}),histories=Array.from({length:20},(_,i)=>item(i+1,{live:true})),original=analyzeHistoricalSimilarity(target,histories,{mode:'original'}),live=analyzeHistoricalSimilarity(target,histories,{mode:'live_adjusted'});assert.equal(original.predictionMode,'original');assert.equal(live.predictionMode,'live_adjusted');assert.equal(extractSimilarityFeatures(target,{mode:'live_adjusted'}).fieldSize,11);assert.equal(extractSimilarityFeatures(target,{mode:'original'}).fieldSize,12)});
test('walk-forward report keeps official prediction delta at zero',()=>{const rows=Array.from({length:30},(_,i)=>item(i+1)),report=walkForwardSimilarity(rows,{maxTargets:30});assert.equal(report.mode,'walk_forward_shadow');assert.equal(report.adopted,false);assert.equal(report.officialPredictionDelta.top3CaptureRate,0);assert.equal(report.officialPredictionDelta.brierScore,0);assert.equal(report.officialPredictionDelta.timeMae,0);assert.ok(report.evaluatedCount>0)});
test('50-race similarity search completes within the non-blocking budget',()=>{const target=item(31),rows=Array.from({length:50},(_,i)=>item(i+1,{prediction:`2026-06-${String((i%28)+1).padStart(2,'0')}T01:00:00.000Z`,result:`2026-06-${String((i%28)+1).padStart(2,'0')}T03:00:00.000Z`,raceId:`history-${i}`})),started=performance.now(),analysis=analyzeHistoricalSimilarity(target,rows);assert.ok(performance.now()-started<2000);assert.equal(analysis.similarRaceCount,50)});
