import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeAuditDate,normalizeRaceId,normalizeAuditSourceRow,metricEligibility,classifyHistoricalRow,auditHistoricalRows,mergeHistoricalRows,summarizeHistoricalLedger} from '../src/research/historical-race-audit.mjs';
test('Race ID normalization is deterministic and JRA/NAR-separated',()=>{assert.equal(normalizeRaceId({date:'2026/09/10',organization:'NAR',track:'KAWASAKI',raceNo:1}),'20260910-NAR-川崎-01');assert.equal(normalizeRaceId({date:'2026-09-10',organization:'JRA',track:'NAK',raceNo:1}),'20260910-JRA-中山-01');});
test('Google serial date normalization',()=>assert.equal(normalizeAuditDate(46273),'20260908'));
test('locale date normalization',()=>{assert.equal(normalizeAuditDate('2026/9/8'),'20260908');assert.equal(normalizeAuditDate('2026-09-08'),'20260908');assert.equal(normalizeAuditDate('20260908'),'20260908');});
test('invalid date fails closed',()=>{assert.equal(normalizeAuditDate('09/08/2026'),null);assert.equal(normalizeAuditDate('2026-02-30'),null);});
test('organization uses header mapping and cannot be a date',()=>{assert.deepEqual(normalizeAuditSourceRow(['開催日','主催'],['2026-09-12','JRA'],{date:'開催日',organization:'主催'}),{date:'20260912',organization:'JRA'});assert.equal(normalizeAuditSourceRow(['主催'],['2026-09-12'],{organization:'主催'}).organization,null);});
test('missing metrics never become zero or composite eligibility',()=>{const e=metricEligibility({preRace:true,resultOfficial:true,aiWin:0,aiPlace:null});assert.equal(e.Eligible_AIWin,true);assert.equal(e.Eligible_AIPlace,false);assert.equal(e.Eligible_CompositeModel,false);});
test('partial and index-only remain safely classified',()=>{assert.equal(classifyHistoricalRow({preRace:true,resultOfficial:true,aiWin:12.3}),'PARTIAL_ELIGIBLE');assert.equal(classifyHistoricalRow({preRace:true,indexOnly:true,indexCluster:'A'}),'INDEX_ONLY');assert.equal(classifyHistoricalRow({reconstructed:true,predictionExists:true}),'REFERENCE_ONLY');});
test('same conceptual race from prediction and index merges once',()=>{const x=mergeHistoricalRows([{originalRaceId:'prediction',date:46273,organization:'NAR',track:'川崎',raceNo:2,preRace:true,predictionExists:true,source:'prediction'},{originalRaceId:'index',date:'2026/09/08',organization:'NAR',track:'KAWASAKI',raceNo:2,preRace:true,indexOnly:true,indexPresent:true,source:'index'}]);assert.equal(x.normalizedRaceCount,1);assert.equal(x.conceptualDuplicatesResolved,1);assert.deepEqual(x.ledger[0].sources,['prediction','index']);});
test('aggregate day row does not count as a race',()=>{const x=mergeHistoricalRows([{originalRaceId:'2026/09/05-統合日次',date:'2026/09/05',track:'JRA複数場'}]);assert.equal(x.ledger.length,0);assert.equal(x.aggregateRows.length,1);});
test('unresolved ID stays null and original ID is preserved',()=>{const x=auditHistoricalRows([{originalRaceId:'20260905-NAK11-KAH',date:'20260905',track:'中山',raceNo:11}]);assert.equal(x[0].Normalized_Race_ID,null);assert.equal(x[0].Original_Race_ID,'20260905-NAK11-KAH');assert.equal(x[0].reviewStatus,'NEEDS_REVIEW');});
test('snapshot provenance is preserved',()=>{const x=auditHistoricalRows([{originalRaceId:'legacy',date:'2026-09-10',organization:'NAR',track:'川崎',raceNo:1,snapshotType:'T-15',predictionTimestamp:'a'}]);assert.equal(x[0].Snapshot_Type,'T-15');});
test('report and hub use identical summary counts',()=>{const rows=mergeHistoricalRows([{date:'20260908',organization:'NAR',track:'川崎',raceNo:2,preRace:true,indexPresent:true,resultOfficial:true,aiWin:1,aiPlace:2,predictedTime:3,final:true}]).ledger;assert.deepEqual(summarizeHistoricalLedger(rows),summarizeHistoricalLedger(rows));assert.equal(summarizeHistoricalLedger(rows).NAR.Index_PreRace_Available_Races,1);});

