import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {provisionMarketQueueAudit as provision,MIGRATION_0013_SHA256,provisionCliArgs} from '../scripts/jra-market-queue-provision.mjs';
const sql=readFileSync(new URL('../migrations/0013_jra_market_queue_audit.sql',import.meta.url),'utf8'),config=JSON.parse(readFileSync(new URL('../wrangler.jsonc',import.meta.url),'utf8'));
function matching(){const p=spawnSync('python3',['-c',`import sqlite3,json,sys\ndb=sqlite3.connect(':memory:');db.row_factory=sqlite3.Row;db.executescript(sys.stdin.read());print(json.dumps({'rows':[dict(r) for r in db.execute('SELECT name,type,"notnull" AS required,pk FROM pragma_table_info("jra_market_queue_events")')],'objects':[dict(r) for r in db.execute('SELECT name,type,sql FROM sqlite_master WHERE tbl_name="jra_market_queue_events"')]}))`],{input:sql,encoding:'utf8'});assert.equal(p.status,0);return JSON.parse(p.stdout)}
test('fixed migration hash identifies exactly the reviewed DDL file',()=>{assert.equal(createHash('sha256').update(sql).digest('hex'),MIGRATION_0013_SHA256);assert.ok(!/\b(?:INSERT|UPDATE|DELETE|DROP|ALTER)\b/i.test(sql))});
test('default plan performs two SELECTs and zero writes',async()=>{let reads=0;const r=await provision({sql,config,execute:async q=>{assert.match(q,/^SELECT /);reads++;return []},applyMigration:async()=>assert.fail()});assert.equal(r.status,'PLAN_ONLY');assert.equal(r.applyAttempted,false);assert.equal(reads,2)});
test('explicit apply creates schema and rechecks it, repeat application skips write',async()=>{const s=matching();let applied=0;const execute=async q=>applied?(q.includes('pragma_table_info')?s.rows:s.objects):[];const options={apply:true,sql,config,execute,applyMigration:async content=>{assert.equal(content,sql);applied++}};assert.equal((await provision(options)).status,'PROVISIONED');assert.equal(applied,1);assert.equal((await provision(options)).status,'ALREADY_PROVISIONED');assert.equal(applied,1)});
test('schema drift refuses repair',async()=>{const s=matching();s.rows[0].pk=0;const r=await provision({apply:true,sql,config,execute:async q=>q.includes('pragma_table_info')?s.rows:s.objects,applyMigration:async()=>assert.fail()});assert.equal(r.status,'BLOCKED');assert.equal(r.applyAttempted,false)});
test('object collision blocks otherwise missing schema',async()=>{const r=await provision({apply:true,sql,config,execute:async q=>q.includes('sqlite_master')?[{name:'collision',type:'index'}]:[],applyMigration:async()=>assert.fail()});assert.equal(r.status,'BLOCKED')});
test('altered migration or wrong database/Queue activation are rejected before queries',async()=>{for(const options of [{sql:sql+'\n'},{config:{...config,vars:{...config.vars,ENABLE_JRA_MARKET_QUEUE:'true'}}},{config:{...config,d1_databases:[]}},{config:{...config,d1_databases:[...config.d1_databases,{binding:'DB',database_name:'wrong'}]}}])await assert.rejects(provision({sql,config,...options,execute:async()=>assert.fail()}),/provision_/)});
test('unavailable schema blocks apply without exposing raw errors',async()=>{const r=await provision({apply:true,sql,config,execute:async()=>{throw Error('secret')},applyMigration:async()=>assert.fail()});assert.equal(r.status,'BLOCKED');assert.ok(!JSON.stringify(r).includes('secret'))});
test('failed apply has unknown outcome and is never automatically retried',async()=>{let count=0;const r=await provision({apply:true,sql,config,execute:async()=>[],applyMigration:async()=>{count++;throw Error('secret')}});assert.equal(r.status,'APPLY_OUTCOME_UNKNOWN');assert.equal(count,1);assert.ok(!JSON.stringify(r).includes('secret'))});
test('failed readback is APPLIED_UNVERIFIED',async()=>{let applied=false;const r=await provision({apply:true,sql,config,execute:async()=>{if(applied)throw Error('offline');return []},applyMigration:async()=>{applied=true}});assert.equal(r.status,'APPLIED_UNVERIFIED')});
test('explicit CLI apply is required and other flags are rejected',()=>{assert.deepEqual(provisionCliArgs([]),{apply:false});assert.deepEqual(provisionCliArgs(['--apply-0013']),{apply:true});assert.throws(()=>provisionCliArgs(['--apply']));assert.throws(()=>provisionCliArgs(['--apply-0013','--force']))});
test('actual SQLite provisioning is idempotent and preserves snapshot/cache rows',async t=>{
 const {mkdtempSync,rmSync}=await import('node:fs'),{tmpdir}=await import('node:os'),{join}=await import('node:path');
 const dir=mkdtempSync(join(tmpdir(),'chass-provision-')),path=join(dir,'d1.sqlite');t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const query=(text,script=false)=>{const p=spawnSync('python3',['-c',`import sqlite3,json,sys\nx=json.load(sys.stdin)\nwith sqlite3.connect(x['path']) as db:\n db.row_factory=sqlite3.Row\n if x['script']:db.executescript(x['sql']);print('[]')\n else:print(json.dumps([dict(r) for r in db.execute(x['sql'])]))`],{input:JSON.stringify({path,sql:text,script}),encoding:'utf8'});assert.equal(p.status,0,p.stderr);return JSON.parse(p.stdout)};
 query("CREATE TABLE precomputed_race_snapshots (snapshot_hash TEXT,data_json TEXT,market_json TEXT); INSERT INTO precomputed_race_snapshots VALUES ('original','data','market'); CREATE TABLE jra_official_cache (payload_json TEXT); INSERT INTO jra_official_cache VALUES ('original_odds');",true);
 const before=JSON.stringify([query('SELECT * FROM precomputed_race_snapshots'),query('SELECT * FROM jra_official_cache')]);let writes=0;
 const args={apply:true,sql,config,execute:async q=>query(q),applyMigration:async s=>{writes++;query(s,true)}};
 assert.equal((await provision(args)).status,'PROVISIONED');assert.equal((await provision(args)).status,'ALREADY_PROVISIONED');assert.equal(writes,1);
 assert.equal(JSON.stringify([query('SELECT * FROM precomputed_race_snapshots'),query('SELECT * FROM jra_official_cache')]),before);assert.deepEqual(query('SELECT * FROM jra_market_queue_events'),[]);
});
