import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createJraMeetingService,parseJraProgram,sourceUrl,FEATURE_DEFAULTS,JRA_TRACKS} from '../jra-meeting-discovery.mjs';
import worker from '../worker.js';
const html=fs.readFileSync(new URL('../jra-program-fixture.html',import.meta.url),'utf8');
const date='2026-09-12',request=()=>new Request('https://app.test/api/jra/meeting?date='+date);
const payload=()=>({ok:true,organization:'JRA',date,meetings:parseJraProgram(html,date)});
test('official DOM excerpt: two meetings, twelve races each, other eight planned non-meetings',()=>{const entries=parseJraProgram(html,date);assert.deepEqual(entries.filter(x=>x.status==='meeting').map(x=>[x.track,x.raceNumbers.length]),[['中山',12],['阪神',12]]);assert.equal(entries.filter(x=>x.status==='non_meeting').length,8);assert.ok(entries.every(x=>x.organization==='JRA'));});
test('date and URL validation rejects impossible dates and arbitrary destinations',()=>{for(const d of ['2026-02-30','https://evil.test','2026-9-12'])assert.throws(()=>sourceUrl(d));assert.equal(sourceUrl(date),'https://www.jra.go.jp/keiba/calendar2026/2026/9/0912.html');});
test('wrong date, duplicate number and truncated page reject rather than invent non-meetings',()=>{for(const input of [html.replace('2026年9月12日','2026年9月13日'),html.replace('2<span>レース','1<span>レース'),html.replace('</html>',''),html.replace('4回阪神3日','4回未知3日')])assert.throws(()=>parseJraProgram(input,date));});
test('changed header and no tables fail structure gate',()=>{assert.throws(()=>parseJraProgram(html.replaceAll('番号','変更'),date));assert.throws(()=>parseJraProgram('<html><h1>2026年9月12日 競馬番組</h1></html>',date));});
test('ten repeated views fetch once; flags off bypass even populated cache',async()=>{let calls=0;const handler=createJraMeetingService({fetchImpl:async()=>{calls++;return new Response(html);}});for(let i=0;i<10;i++){const res=await handler(request());assert.equal(res.status,200);assert.equal(res.headers.get('X-CHASS-Meeting-Cache'),i?'HIT':'MISS');}const off=await handler(request(),{ENABLE_JRA_MEETING_DISCOVERY:'false'});assert.equal((await off.json()).status,'unknown');assert.equal(calls,1);});
test('concurrent requests single-flight and no redirect following',async()=>{let calls=0;const handler=createJraMeetingService({fetchImpl:async(url,options)=>{calls++;assert.equal(options.redirect,'error');await new Promise(r=>setTimeout(r,10));return new Response(html);}});const results=await Promise.all(Array.from({length:10},()=>handler(request())));assert.equal(calls,1);assert.ok(results.every(x=>x.status===200));});
test('network, 404, 403 and parser errors yield unknown and negative cache',async()=>{for(const failure of ['network',404,403,'parser']){let calls=0;const handler=createJraMeetingService({fetchImpl:async()=>{calls++;if(failure==='network')throw Error('network');return new Response(failure==='parser'?'bad':'',{status:typeof failure==='number'?failure:200});}});for(let i=0;i<2;i++){const body=await (await handler(request())).json();assert.equal(body.status,'unknown');assert.ok(body.meetings.every(x=>x.status==='unknown'));}assert.equal(calls,1);}});
test('timeout terminates loading without retries',async()=>{let calls=0;const handler=createJraMeetingService({timeoutMs:10,fetchImpl:()=>{calls++;return new Promise(()=>{});}});assert.equal((await (await handler(request())).json()).error,'JRA_FETCH_TIMEOUT');assert.equal(calls,1);});
test('cache expires, with longer TTL for past dates',async()=>{let clock=Date.parse('2026-09-09T00:00:00Z'),calls=0;const handler=createJraMeetingService({now:()=>clock,fetchImpl:async()=>{calls++;return new Response(html);}});assert.equal((await (await handler(request())).json()).cacheTtlSeconds,1200);clock+=1200001;await handler(request());assert.equal(calls,2);clock=Date.parse('2026-09-14T00:00:00Z');assert.equal((await (await handler(request())).json()).cacheTtlSeconds,86400);});
test('oversized body fails safely',async()=>{const handler=createJraMeetingService({fetchImpl:async()=>new Response('x'.repeat(524289))});assert.equal((await (await handler(request())).json()).status,'unknown');});
test('three structure failures pause new official requests',async()=>{let calls=0;const handler=createJraMeetingService({fetchImpl:async()=>{calls++;return new Response('broken');}});for(const d of ['12','13','14'])await handler(new Request('https://app.test/api/jra/meeting?date=2026-09-'+d));const result=await handler(new Request('https://app.test/api/jra/meeting?date=2026-09-15'));assert.equal((await result.json()).error,'JRA_AUTO_FETCH_PAUSED');assert.equal(calls,3);});
test('Worker route with disabled flag requires no D1 or external fetch',async()=>{const response=await worker.fetch(request(),{ENABLE_JRA_MEETING_DISCOVERY:'false'});assert.equal((await response.json()).error,'JRA_MEETING_DISCOVERY_DISABLED');assert.equal(FEATURE_DEFAULTS.ENABLE_JRA_AUTO_FETCH,false);assert.equal(FEATURE_DEFAULTS.ENABLE_JRA_ODDS_FETCH,false);assert.equal(FEATURE_DEFAULTS.ENABLE_JRA_RESULT_FETCH,false);});
test('invalid API date and method reject before fetching',async()=>{const handler=createJraMeetingService({fetchImpl:()=>{throw Error('unexpected');}});assert.equal((await handler(new Request('https://app.test/api/jra/meeting?date=bad'))).status,400);assert.equal((await handler(new Request(request(),{method:'POST'}))).status,405);});
function ui(fetchImpl,features={}){
  class Option{constructor(text,value){this.textContent=text;this.value=value;this.disabled=false;}}
  class Element{constructor(value=''){this._value=value;this.options=[];this.events={};this.textContent='';}get value(){return this._value;}set value(v){this._value=String(v);}get selectedOptions(){return this.options.filter(x=>x.value===this.value);}replaceChildren(...children){this.options=children;this.value=children[0]?.value||'';}addEventListener(name,fn){(this.events[name]??=[]).push(fn);}emit(name){for(const fn of this.events[name]||[])fn();}}
  const ids=['jraDate','jraCourse','jraRaceNo','jraMeetingStatus','jraMeetingRefresh','jraManualFallback','jraDataFile'];const elements=Object.fromEntries(ids.map(id=>[id,new Element()]));elements.jraDate.value=date;elements.jraCourse.options=JRA_TRACKS.map(x=>new Option(x,x));elements.jraCourse.value='札幌';elements.jraRaceNo.value='1';let active=true,changes=0,appGeneration=0;
  const context={window:{CHASS_FEATURES:features},document:{getElementById:id=>elements[id]},Option,fetch:fetchImpl,AbortController,setTimeout,clearTimeout};vm.runInNewContext(fs.readFileSync(new URL('../jra-meeting-selector.js',import.meta.url),'utf8'),context);
  const selector=context.window.CHASS_JRA_MEETING.create({isActive:()=>active,getGeneration:()=>appGeneration,onSelection:()=>changes++});return {elements,selector,setInactive(){active=false;selector.setActive(false);},changeGeneration(){appGeneration++;},get changes(){return changes;}};
}
const settle=()=>new Promise(r=>setTimeout(r,20));
test('UI activates only scheduled tracks, with manual option restoring all ten',async()=>{const u=ui(async()=>Response.json(payload()));u.selector.setActive(true);await settle();assert.equal(u.elements.jraCourse.value,'中山');assert.equal(u.elements.jraCourse.options.filter(x=>x.disabled).length,8);assert.equal(u.elements.jraRaceNo.options.length,12);assert.equal(u.changes,1);u.selector.manual();assert.ok(u.elements.jraCourse.options.every(x=>!x.disabled));});
test('UI fetch failure permits manual selection',async()=>{const u=ui(async()=>{throw Error('offline');});u.selector.setActive(true);await settle();assert.match(u.elements.jraMeetingStatus.textContent,/不明/);assert.equal(u.changes,0);assert.equal(u.elements.jraRaceNo.options.length,12);});
test('UI feature off performs zero requests',async()=>{const u=ui(()=>{throw Error('unexpected');},{ENABLE_JRA_MEETING_DISCOVERY:false});u.selector.setActive(true);await settle();assert.match(u.elements.jraMeetingStatus.textContent,/手動/);assert.equal(u.changes,0);});
test('late response cannot change NAR, changed date, changed generation or manual fallback',async()=>{for(const transition of ['NAR','date','generation','manual']){let release;const u=ui(()=>new Promise(r=>release=r));u.selector.setActive(true);if(transition==='NAR')u.setInactive();if(transition==='date')u.elements.jraDate.value='2026-09-13';if(transition==='generation')u.changeGeneration();if(transition==='manual')u.selector.manual();release(Response.json(payload()));await settle();assert.equal(u.changes,0);assert.equal(u.elements.jraCourse.value,'札幌');u.selector.manual();}});
test('saved snapshot mode performs zero discovery requests',()=>{let count=0;const u=ui(()=>count++);u.selector.setActive(true,{discover:false});assert.equal(count,0);assert.equal(u.changes,0);});
