import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {parseJraWinOdds,createJraOddsService,JRA_ODDS_PARSER_VERSION} from '../jra-odds-fetch.mjs';
import worker from '../worker.js';
const html=fs.readFileSync(new URL('../jra-race-card-fixture.html',import.meta.url),'utf8');
const query={date:'2026-09-05',track:'中山',race:5},token='pw01dde0106202604010520260905/16';
const listing=`<html><body><a href="/JRADB/accessD.html?CNAME=${token}">5R</a></body></html>`;
const request=()=>new Request('https://app.test/api/jra/odds?date=2026-09-05&track='+encodeURIComponent('中山')+'&race=5');
test('official card extracts horse-number keyed win odds and popularity',()=>{const data=parseJraWinOdds(html,query);assert.equal(data.parserVersion,JRA_ODDS_PARSER_VERSION);assert.deepEqual(data.odds,[{horseNo:1,odds:163.3,popularity:11},{horseNo:2,odds:3.2,popularity:2},{horseNo:9,odds:48.3,popularity:7}]);assert.equal(data.quality.oddsCoverage,1);assert.equal(data.marketDataSource,'JRA_OFFICIAL_WIN_ODDS');});
test('final label is explicit and partial publication remains partial',()=>{const final=parseJraWinOdds(html.replace('</body>','<p>オッズは最終オッズ</p></body>'),query);assert.equal(final.oddsSnapshotType,'final');const partial=parseJraWinOdds(html.replace('<strong class="red">3.2</strong>','<strong>---</strong>'),query);assert.equal(partial.quality.complete,false);assert.equal(partial.quality.oddsHorseCount,2);});
test('unpublished and malformed odds are separated',()=>{const none=html.replace(/<div class="odds"><div class="odds_line">[\s\S]*?<\/div><\/div>/g,'<div class="odds">---</div>');assert.throws(()=>parseJraWinOdds(none.replace('</body>','<p>発売前</p></body>'),query),/JRA_ODDS_UNAVAILABLE/);assert.throws(()=>parseJraWinOdds(none,query),/JRA_ODDS_PARSE_ERROR/);});
test('current scratched runner is excluded from odds coverage',()=>{const changed=html.replace('<td class="past p1"></td>','<span>出走取消</span><td class="past p1"></td>');const data=parseJraWinOdds(changed,query);assert.equal(data.quality.activeHorseCount,2);assert.equal(data.quality.oddsHorseCount,2);assert.ok(!data.odds.some(x=>x.horseNo===1));});
test('feature flag off makes zero official requests',async()=>{let calls=0;const service=createJraOddsService({fetchImpl:async()=>{calls++;return new Response('')}}),res=await service(request(),{});assert.equal(res.status,503);assert.equal((await res.json()).error,'JRA_ODDS_FETCH_DISABLED');assert.equal(calls,0);});
test('manual odds service uses listing and card, then minimum interval cache',async()=>{let calls=0;const service=createJraOddsService({fetchImpl:async url=>{calls++;return new Response(url.includes('pw01dli00')?listing:html)}});const first=await service(request(),{ENABLE_JRA_ODDS_FETCH:'true'}),body=await first.json();assert.equal(first.status,200);assert.equal(body.odds.length,3);assert.equal(calls,2);const second=await service(request(),{ENABLE_JRA_ODDS_FETCH:true});assert.equal(second.headers.get('X-CHASS-JRA-Odds-Cache'),'HIT');assert.equal(calls,2);});
test('concurrent requests single-flight and fetch failures do not retry',async()=>{let calls=0;const service=createJraOddsService({fetchImpl:async url=>{calls++;await new Promise(r=>setTimeout(r,5));return new Response(url.includes('pw01dli00')?listing:html)}});const rs=await Promise.all(Array.from({length:5},()=>service(request(),{ENABLE_JRA_ODDS_FETCH:true})));assert.ok(rs.every(x=>x.status===200));assert.equal(calls,2);let failures=0;const failed=createJraOddsService({fetchImpl:async()=>{failures++;throw Error('offline')}});assert.equal((await (await failed(request(),{ENABLE_JRA_ODDS_FETCH:true})).json()).error,'JRA_OFFICIAL_UNAVAILABLE');assert.equal(failures,1);});
test('Worker odds endpoint validates method and feature flag',async()=>{const bad=await worker.fetch(new Request('https://app.test/api/jra/odds?date=bad&track=x&race=99'),{});assert.equal(bad.status,400);const disabled=await worker.fetch(request(),{});assert.equal(disabled.status,503);const post=await worker.fetch(new Request(request().url,{method:'POST'}),{ENABLE_JRA_ODDS_FETCH:true});assert.equal(post.status,405);});
function uiClient(fetchImpl){class E{constructor(){this.disabled=false;this.textContent='';}}const elements={liveOddsSync:new E(),liveOddsStatus:new E()};let active=true,generation=1,applied=0;const context={window:{},document:{getElementById:id=>elements[id]},fetch:fetchImpl,AbortController,URLSearchParams,setTimeout,clearTimeout};vm.runInNewContext(fs.readFileSync(new URL('../jra-odds-client.js',import.meta.url),'utf8'),context);const api=context.window.CHASS_JRA_ODDS_CLIENT.create({isActive:()=>active,getSelection:()=>query,getGeneration:()=>generation,apply:()=>applied++});api.setActive(true);return {api,elements,get applied(){return applied},stale(){generation++},off(){active=false;api.setActive(false)}};}
const payload={ok:true,odds:[{horseNo:1,odds:3.2,popularity:1}],quality:{oddsHorseCount:1,activeHorseCount:1},oddsSnapshotType:'live'};
test('odds UI applies explicit response and explains disabled flag',async()=>{const good=uiClient(async()=>Response.json(payload));await good.api.load();assert.equal(good.applied,1);assert.match(good.elements.liveOddsStatus.textContent,/1\/1頭反映/);const off=uiClient(async()=>Response.json({ok:false,error:'JRA_ODDS_FETCH_DISABLED'},{status:503}));await off.api.load();assert.equal(off.applied,0);assert.match(off.elements.liveOddsStatus.textContent,/ENABLE_JRA_ODDS_FETCH/);});
test('stale odds response never updates another race',async()=>{let release;const c=uiClient(()=>new Promise(r=>release=r));const p=c.api.load();c.stale();release(Response.json(payload));await p;assert.equal(c.applied,0);});
async function core(){const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8'),window={__CHASS_TEST__:true},memory=new Map(),document={getElementById(){return {value:'',textContent:'',addEventListener(){},classList:{toggle(){}}}},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},console,setTimeout,clearTimeout,setInterval,clearInterval,Date,Math,JSON,Map,Set,URL,Blob,TextEncoder,structuredClone};const context={window,document,...window};vm.createContext(context);vm.runInContext(source,context,{filename:'app.js'});return window.CHASS_TEST;}
test('market odds preserve frozen prediction ability and create separate market snapshot',async()=>{const c=await core(),race={category:'中央競馬',raceType:'JRA',raceDate:'2026-09-05',track:'中山',raceNo:5,distance:2000,surface:'芝',oddsType:'none'},horses=[1,2,9].map((horseNo,i)=>({horseNo,horseName:'馬'+horseNo,win:30-i*5,place:60-i*5,overall:90-i*5,predictedTime:`2:0${i}.0`,abilityMark:''}));c.setState({race,horses,result:null,actualTimes:{},finalSnapshot:null,predictionSnapshot:null,marketSnapshot:null,validationCompleted:false});c.makeSnapshot();const before=JSON.stringify(c.getState().predictionSnapshot),ability=c.getState().horses.map(x=>[x.horseNo,x.win,x.place,x.overall,x.predictedTime]);c.applyMarketOdds([{horseNo:1,odds:10,popularity:2},{horseNo:2,odds:3,popularity:1},{horseNo:9,odds:20,popularity:3}],'2026-09-05T00:00:00.000Z',{marketDataSource:'JRA_OFFICIAL_WIN_ODDS'});assert.equal(JSON.stringify(c.getState().predictionSnapshot),before);assert.deepEqual(c.getState().horses.map(x=>[x.horseNo,x.win,x.place,x.overall,x.predictedTime]),ability);assert.equal(c.getState().marketSnapshot.marketDataSource,'JRA_OFFICIAL_WIN_ODDS');});
