import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {handleJraMeetingPersistent,jraMeetingRefreshTargets,jraMeetingRefreshTtl,runScheduledJraMeetingRefresh} from '../jra-background-refresh.mjs';
import {fetchScheduledJraResult,runScheduledTasks} from '../worker.js';
const meetings=date=>['札幌','函館','福島','新潟','東京','中山','中京','京都','阪神','小倉'].map((track,i)=>({organization:'JRA',date,track,status:i===5?'meeting':'non_meeting',raceNumbers:i===5?[1,2,3,4,5,6,7,8,9,10,11,12]:[]}));
class MeetingDb{constructor(){this.rows=new Map();this.writes=0}prepare(sql){const db=this;return {args:[],bind(...args){this.args=args;return this},async first(){if(sql.includes('FROM jra_meeting_calendar WHERE date='))return db.rows.get(this.args[0])||null;return null},async run(){if(sql.startsWith('INSERT INTO jra_meeting_calendar')){const a=this.args;db.rows.set(a[0],{date:a[0],status:a[1],meetings_json:a[2],checked_at:a[3],next_refresh_at:a[4],source:a[5],parser_version:a[6],error_code:a[7]});db.writes++}return {success:true}}}}}
const responseFor=date=>new Response(JSON.stringify({ok:true,status:'meeting',organization:'JRA',date,meetings:meetings(date),source:'JRA_OFFICIAL',parserVersion:'jra-program-v1'}),{status:200,headers:{'content-type':'application/json'}});
test('Tokyo refresh targets are today and tomorrow only',()=>{assert.deepEqual(jraMeetingRefreshTargets(new Date('2026-09-09T00:00:00Z')),['2026-09-09','2026-09-10']);assert.equal(jraMeetingRefreshTtl('2026-09-09',new Date('2026-09-09T00:00:00Z')),30*60_000);assert.equal(jraMeetingRefreshTtl('2026-09-10',new Date('2026-09-09T00:00:00Z')),6*60*60_000);});
test('background meeting flag off performs zero official requests',async()=>{const DB=new MeetingDb();let calls=0;const out=await runScheduledJraMeetingRefresh(DB,{now:new Date('2026-09-09T00:00:00Z'),env:{ENABLE_JRA_BACKGROUND_REFRESH:'false',ENABLE_JRA_MEETING_DISCOVERY:'true'},handler:async()=>{calls++;return responseFor('2026-09-09')}});assert.equal(out.reason,'feature_disabled');assert.equal(calls,0);});
test('scheduled meeting refresh fetches one date per cron and then uses D1 freshness',async()=>{const DB=new MeetingDb();let calls=0;const handler=async request=>{calls++;return responseFor(new URL(request.url).searchParams.get('date'))},options={now:new Date('2026-09-09T00:00:00Z'),env:{DB,ENABLE_JRA_BACKGROUND_REFRESH:'true',ENABLE_JRA_MEETING_DISCOVERY:'true'},handler};const first=await runScheduledJraMeetingRefresh(DB,options),second=await runScheduledJraMeetingRefresh(DB,options),third=await runScheduledJraMeetingRefresh(DB,options);assert.equal(first.date,'2026-09-09');assert.equal(second.date,'2026-09-10');assert.equal(third.reason,'fresh_cache');assert.equal(calls,2);assert.equal(DB.writes,2);});
test('interactive meeting route reuses the isolated JRA D1 cache',async()=>{const DB=new MeetingDb(),now=Date.parse('2026-09-09T00:00:00Z');let calls=0;const handler=async request=>{calls++;return responseFor(new URL(request.url).searchParams.get('date'))},request=new Request('https://app.test/api/jra/meeting?date=2026-09-09');let response=await handleJraMeetingPersistent(request,{DB},{handler,now:()=>now});assert.equal(response.headers.get('X-CHASS-Meeting-Cache'),'D1-MISS');response=await handleJraMeetingPersistent(request,{DB},{handler,now:()=>now});assert.equal(response.headers.get('X-CHASS-Meeting-Cache'),'D1-HIT');assert.equal(calls,1);assert.equal((await response.json()).meetings[5].track,'中山');});
test('unknown meeting is cached briefly and never converted to non-meeting',async()=>{const DB=new MeetingDb(),now=Date.parse('2026-09-09T00:00:00Z');let calls=0;const handler=async()=>{calls++;return Response.json({ok:false,status:'unknown',organization:'JRA',date:'2026-09-09',error:'JRA_OFFICIAL_UNAVAILABLE',meetings:[]},{status:503})},request=new Request('https://app.test/api/jra/meeting?date=2026-09-09');await handleJraMeetingPersistent(request,{DB},{handler,now:()=>now});const cached=await handleJraMeetingPersistent(request,{DB},{handler,now:()=>now}),body=await cached.json();assert.equal(cached.status,503);assert.equal(body.status,'unknown');assert.equal(body.error,'JRA_OFFICIAL_UNAVAILABLE');assert.equal(calls,1);});
test('scheduled JRA result adapter preserves official errors and complete data',async()=>{const good=await fetchScheduledJraResult({date:'2026-09-09',track:'中山',race:1,env:{ENABLE_JRA_RESULT_FETCH:'true'},handler:async()=>Response.json({ok:true,finishOrder:[4,11,9],results:[{horseNo:4}],actualTimes:{4:'1:53.0'},source:'JRA_OFFICIAL'})});assert.deepEqual(good.finishOrder,[4,11,9]);await assert.rejects(()=>fetchScheduledJraResult({date:'2026-09-09',track:'中山',race:1,handler:async()=>Response.json({ok:false,error:'JRA_RESULT_UNPUBLISHED'},{status:409})}),error=>error.code==='JRA_RESULT_UNPUBLISHED');});
test('scheduled priority is result, one meeting refresh, history, research',async()=>{const calls=[];const result=await runScheduledTasks({}, {env:{},resultRunner:async()=>{calls.push('result');return {processed:0}},meetingRunner:async()=>{calls.push('meeting');return {processed:1}},historicalRunner:async()=>{calls.push('history');return {processed:0}},researchRunner:async()=>{calls.push('research');return {processed:0}}});assert.deepEqual(calls,['result','meeting','history','research']);assert.equal(result.jraMeeting.processed,1);});
test('J5 source never background-fetches all race cards or odds',()=>{const source=fs.readFileSync(new URL('../jra-background-refresh.mjs',import.meta.url),'utf8'),worker=fs.readFileSync(new URL('../worker.js',import.meta.url),'utf8'),migration=fs.readFileSync(new URL('../migrations/0006_jra_background_refresh.sql',import.meta.url),'utf8');assert.doesNotMatch(source,/jra\/race|jra\/odds|for\s*\([^)]*race/i);assert.match(worker,/organization==='JRA'\?await fetchScheduledJraResult/);assert.match(worker,/predictionSnapshot:prediction,marketSnapshot:parseJson\(row\.market_json\),finalSnapshot:parseJson\(row\.final_json\)/);assert.match(migration,/jra_meeting_calendar/);assert.doesNotMatch(migration,/\b(?:DROP|DELETE|UPDATE|ALTER)\b/i);});
