import test from 'node:test';
import assert from 'node:assert/strict';
import {saveNarEarly,readNarEarly} from '../src/research/nar-early-store.mjs';
const raceId='2026-10-07|川崎|1',now=Date.parse('2026-10-07T01:00:00Z');
function hash(v){const canonical=x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(canonical).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';let h=2166136261;for(const c of canonical(v).split(''))h=Math.imul(h^c.charCodeAt(0),16777619);return 'fnv1a32:'+(h>>>0).toString(16).padStart(8,'0')}
function record(odds=3){const at=new Date(now).toISOString(),race={raceType:'NAR',raceDate:'2026-10-07',track:'川崎',raceNo:1,postTime:'15:00'},r={race,predictionSnapshot:{race,createdAt:at,generatedAt:at,horses:[{horseNo:1,abilityMark:'◎'},{horseNo:2,valueMark:'💎'}]},marketSnapshot:{createdAt:at,horses:[{horseNo:1,odds}]},finalSnapshot:{createdAt:at,top3:[{horseNo:1}]}};r.snapshotIntegrity={algorithm:'FNV-1a-32/canonical-json',sealedAt:at,hashes:Object.fromEntries(['predictionSnapshot','marketSnapshot','finalSnapshot'].map(k=>[k,hash(r[k])]))};return r}
function memory(){const data=new Map(),calls=[];return {data,calls,async get(k){calls.push('read');return data.has(k)?data.get(k):null},async insertIfAbsent(k,v){calls.push('insert');if(data.has(k))return false;data.set(k,v);return true}}}
const save=(store,options={})=>saveNarEarly({store,raceId,record:record(),now,freshAcquisition:true,...options});
test('JSON roundtrip preserves original signals and immutable first version',async()=>{const store=memory(),first=await save(store),read=await readNarEarly({store,raceId});assert.equal(first.status,'CREATED');assert.deepEqual(read.snapshot,first.snapshot);assert.equal(read.snapshot.data.predictionSnapshot.horses[1].valueMark,'💎');assert.throws(()=>read.snapshot.data.marketSnapshot.horses[0].odds=99);assert.equal(first.snapshot.formalKpiEligible,false)});
test('later results and odds never replace a stored first version',async()=>{const store=memory(),first=await save(store),before=[...store.data.values()][0],r=record(99);r.resultSnapshot={};const next=await save(store,{record:r,now:now+12*3600_000,freshAcquisition:false});assert.equal(next.status,'PRESERVED');assert.deepEqual(next.snapshot,first.snapshot);assert.equal([...store.data.values()][0],before);assert.equal(store.calls.filter(x=>x==='insert').length,1)});
test('two concurrent candidates retain the atomic winner',async()=>{const store=memory(),all=await Promise.all([save(store),save(store,{record:record(99)})]);assert.deepEqual(all.map(x=>x.status).sort(),['CREATED','PRESERVED']);assert.equal(all[0].snapshot.contentSha256,all[1].snapshot.contentSha256);assert.equal(store.data.size,1)});
test('corrupt or malformed existing data fails closed with no insert',async()=>{for(const raw of ['{broken','{}',undefined]){const store=memory();store.data.set('nar-early:v1:'+raceId,raw);assert.equal((await save(store)).status,'REJECTED');assert.equal(store.calls.includes('insert'),false)}});
test('tampered stored odds never fall forward',async()=>{const store=memory();await save(store);const key=[...store.data.keys()][0],value=JSON.parse(store.data.get(key));value.data.marketSnapshot.horses[0].odds=99;store.data.set(key,JSON.stringify(value));const count=store.calls.length;assert.equal((await save(store)).reason,'EARLY_CONTENT_MISMATCH');assert.deepEqual(store.calls.slice(count),['read'])});
test('missing read and invalid candidates perform no insert',async()=>{const store=memory();assert.equal((await readNarEarly({store,raceId})).status,'MISSING');assert.equal((await save(store,{freshAcquisition:false})).reason,'FRESH_ACQUISITION_REQUIRED');assert.equal(store.calls.includes('insert'),false)});
test('read/write errors and invalid storage contracts are rejected',async()=>{assert.equal((await save({get(){throw Error('private')},insertIfAbsent(){assert.fail('must not write')}})).reason,'STORE_READ_FAILED');assert.equal((await save({get(){return null},insertIfAbsent(){throw Error('private')}})).reason,'STORE_WRITE_FAILED');assert.equal((await save({get(){return null},insertIfAbsent(){return undefined}})).reason,'STORE_INSERT_CONTRACT_INVALID');assert.equal((await readNarEarly({store:memory(),raceId:'wrong'})).reason,'STORE_CONTRACT_INVALID')});
test('lost write and corrupted concurrent winner are rejected without retry',async()=>{for(const inserted of [true,false]){let reads=0,inserts=0;const store={get(){return ++reads===1?null:inserted?null:'{}'},insertIfAbsent(){inserts++;return inserted}};assert.equal((await save(store)).status,'REJECTED');assert.equal(inserts,1)}});
test('successful insert must read back the same candidate',async()=>{const other=memory();await save(other,{record:record(99)});let reads=0;const store={get(){return ++reads===1?null:[...other.data.values()][0]},insertIfAbsent(){return true}};assert.equal((await save(store)).reason,'STORE_READBACK_MISMATCH')});
