import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createNarEarlySqlStore,NAR_EARLY_RESEARCH_SCHEMA_SQL} from '../src/research/nar-early-sql-store.mjs';
import {freezeNarEarlySnapshot} from '../src/research/nar-early-freeze.mjs';
import {saveNarEarly,readNarEarly} from '../src/research/nar-early-store.mjs';
const raceId='2026-10-07|川崎|1',key='nar-early:v1:'+raceId,now=Date.parse('2026-10-07T01:00:00Z');
function record(odds=3){const at=new Date(now).toISOString(),race={raceType:'NAR',raceDate:'2026-10-07',track:'川崎',raceNo:1,postTime:'15:00'},r={race,predictionSnapshot:{race,createdAt:at,generatedAt:at,horses:[{horseNo:1,abilityMark:'◎'},{horseNo:2,valueMark:'💎'}]},marketSnapshot:{createdAt:at,horses:[{horseNo:1,odds}]},finalSnapshot:{createdAt:at,top3:[{horseNo:1}]}};const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';const hash=v=>{let h=2166136261;for(const c of canonical(v).split(''))h=Math.imul(h^c.charCodeAt(0),16777619);return 'fnv1a32:'+(h>>>0).toString(16).padStart(8,'0')};r.snapshotIntegrity={algorithm:'FNV-1a-32/canonical-json',sealedAt:at,hashes:Object.fromEntries(['predictionSnapshot','marketSnapshot','finalSnapshot'].map(k=>[k,hash(r[k])]))};return r}
const save=(store,options={})=>saveNarEarly({store,raceId,record:record(),now,freshAcquisition:true,...options});
const python=`import json,sqlite3,sys
x=json.load(sys.stdin)
with sqlite3.connect(x['path']) as db:
 db.row_factory=sqlite3.Row
 c=db.execute(x['sql'],x['args'])
 print(json.dumps((dict(r) if (r:=c.fetchone()) is not None else None) if x['first'] else {'success':True,'meta':{'changes':max(c.rowcount,0)}}))`;
function local(t,setup=true){const directory=mkdtempSync(join(tmpdir(),'chass-early-sql-')),path=join(directory,'research.sqlite');t.after(()=>rmSync(directory,{recursive:true,force:true}));const calls=[];function query(sql,args=[],first=false){calls.push(sql);const p=spawnSync('python3',['-c',python],{input:JSON.stringify({path,sql,args,first}),encoding:'utf8'});if(p.status!==0)throw Error('LOCAL_SQL_ERROR');return JSON.parse(p.stdout)}const db={prepare(sql){return {bind(...args){return {async first(){return query(sql,args,true)},async run(){return query(sql,args)}}}}}};if(setup)query(NAR_EARLY_RESEARCH_SCHEMA_SQL);return {db,calls,query,store:createNarEarlySqlStore({db,mode:'research-write'})}}
test('real local SQLite roundtrip retains marks and serialized first version',async t=>{const {store}=local(t),first=await save(store),read=await readNarEarly({store,raceId});assert.equal(first.status,'CREATED');assert.deepEqual(read.snapshot,first.snapshot);assert.equal(read.snapshot.data.predictionSnapshot.horses[1].valueMark,'💎')});
test('two SQL adapters with competing candidates preserve one winner',async t=>{const {db,store,query}=local(t),second=createNarEarlySqlStore({db,mode:'research-write'}),results=await Promise.all([save(store),save(second,{record:record(99)})]);assert.deepEqual(results.map(x=>x.status).sort(),['CREATED','PRESERVED']);assert.equal(results[0].snapshot.contentSha256,results[1].snapshot.contentSha256);assert.equal(query('SELECT count(*) AS n FROM research_nar_early_snapshots',[],true).n,1)});
test('default OFF and read-only writes issue zero SQL',async()=>{let calls=0;const db={prepare(){calls++;assert.fail('SQL must not run')}};await assert.rejects(createNarEarlySqlStore({db}).get(key));await assert.rejects(createNarEarlySqlStore({db,mode:'read-only'}).insertIfAbsent(key,'{}'));assert.equal(calls,0)});
test('read-only mode can restore existing first version without replacing it',async t=>{const {db,store,calls}=local(t),first=await save(store),readonly=createNarEarlySqlStore({db,mode:'read-only'}),start=calls.length;const restored=await save(readonly,{freshAcquisition:false,now:now+999999});assert.deepEqual(restored.snapshot,first.snapshot);assert.equal(restored.status,'PRESERVED');assert.equal(calls.slice(start).every(sql=>sql.startsWith('SELECT')),true)});
test('missing table fails closed and never auto-migrates',async t=>{const {store,calls}=local(t,false);assert.equal((await save(store)).status,'REJECTED');assert.equal(calls.some(sql=>/CREATE|INSERT/.test(sql)),false)});
test('corrupt existing row is never repaired or replaced',async t=>{const {store,query,calls}=local(t);query('INSERT INTO research_nar_early_snapshots VALUES (?,?)',[key,'{}']);const start=calls.length;assert.equal((await save(store)).status,'REJECTED');assert.equal(calls.slice(start).every(sql=>sql.startsWith('SELECT')),true);assert.equal(query('SELECT snapshot_json FROM research_nar_early_snapshots WHERE storage_key=?',[key],true).snapshot_json,'{}')});
test('invalid keys or snapshots are rejected before SQL',async()=>{let calls=0;const store=createNarEarlySqlStore({db:{prepare(){calls++;assert.fail()}},mode:'research-write'});await assert.rejects(store.get("bad' OR 1=1"));await assert.rejects(store.insertIfAbsent(key,'{}'));await assert.rejects(store.insertIfAbsent(key,'bad'));assert.equal(calls,0)});
test('unconfirmed SQL write never claims success',async()=>{const first=await freezeNarEarlySnapshot({raceId,record:record(),now,freshAcquisition:true});for(const result of [{},{success:false,meta:{changes:1}},{success:true,meta:{changes:2}}]){const store=createNarEarlySqlStore({mode:'research-write',db:{prepare(){return {bind(){return {run(){return result}}}}}}});await assert.rejects(store.insertIfAbsent(key,JSON.stringify(first.snapshot)))}});
