import test from 'node:test';
import assert from 'node:assert/strict';
import {captureNarEarlyResearch} from '../src/research/nar-early-capture.mjs';
const raceId='2026-10-07|川崎|1',now=Date.parse('2026-10-07T01:00:00Z'),at=new Date(now).toISOString();
function record(odds=3){const race={raceType:'NAR',raceDate:'2026-10-07',track:'川崎',raceNo:1,postTime:'15:00'},r={race,predictionSnapshot:{race,createdAt:at,generatedAt:at,horses:[{horseNo:1,abilityMark:'◎'},{horseNo:2,valueMark:'💎'}]},marketSnapshot:{createdAt:at,horses:[{horseNo:1,odds}]},finalSnapshot:{createdAt:at,top3:[{horseNo:1}]}};const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';const hash=v=>{let h=2166136261;for(const c of canonical(v).split(''))h=Math.imul(h^c.charCodeAt(0),16777619);return 'fnv1a32:'+(h>>>0).toString(16).padStart(8,'0')};r.snapshotIntegrity={algorithm:'FNV-1a-32/canonical-json',sealedAt:at,hashes:Object.fromEntries(['predictionSnapshot','marketSnapshot','finalSnapshot'].map(k=>[k,hash(r[k])]))};return r}
function memory(){const data=new Map(),calls=[];return {data,calls,async get(key){calls.push('read');return data.has(key)?data.get(key):null},async insertIfAbsent(key,json){calls.push('insert');if(data.has(key))return false;data.set(key,json);return true}}}
const receipt=(r=record())=>({record:r,acquiredAt:at,acquisitionKind:'fresh'});
const run=(store,options={})=>captureNarEarlyResearch({enabled:true,store,raceId,clock:()=>now,acquire:()=>receipt(),...options});
test('default disabled does zero acquisition, clock and storage I/O',async()=>{const fail=()=>assert.fail('must not run');assert.equal((await captureNarEarlyResearch({store:{get:fail,insertIfAbsent:fail},clock:fail,acquire:fail})).status,'DISABLED')});
test('one fresh acquisition freezes original seals and marks without mutating source',async()=>{const store=memory(),r=record(),before=structuredClone(r);let calls=0;const x=await run(store,{acquire:arg=>{calls++;assert.deepEqual(arg,{raceId});return receipt(r)}});assert.equal(x.status,'CREATED');assert.equal(calls,1);assert.deepEqual(r,before);assert.deepEqual(x.snapshot.data.sourceIntegrity,r.snapshotIntegrity);assert.equal(x.snapshot.data.predictionSnapshot.horses[1].valueMark,'💎');assert.equal(x.snapshot.formalKpiEligible,false)});
test('stored first version returns without acquiring later odds or results',async()=>{const store=memory(),first=await run(store);const second=await run(store,{clock:()=>now+12*3600_000,acquire:()=>assert.fail('must not acquire')});assert.equal(second.status,'PRESERVED');assert.deepEqual(second.snapshot,first.snapshot);assert.equal(store.calls.filter(x=>x==='insert').length,1)});
test('corrupt first version never reacquires or writes',async()=>{const store=memory();store.data.set('nar-early:v1:'+raceId,'{}');assert.equal((await run(store,{acquire:()=>assert.fail('must not acquire')})).status,'REJECTED');assert.deepEqual(store.calls,['read'])});
test('acquisition failure and missing acquisition hook never save or retry',async()=>{for(const acquire of [undefined,()=>{throw Error('private source detail')}]){const store=memory();let calls=0;const x=await run(store,{acquire:acquire?()=>{calls++;return acquire()}:undefined});assert.equal(x.status,'REJECTED');assert.equal(calls<=1,true);assert.equal(store.calls.includes('insert'),false)}});
test('stale, future or non-fresh receipts are rejected without writes',async()=>{for(const patch of [{acquisitionKind:'cache'},{acquiredAt:new Date(now-1).toISOString()},{acquiredAt:new Date(now+1).toISOString()},{acquiredAt:'bad'}]){const store=memory();assert.equal((await run(store,{acquire:()=>({...receipt(),...patch})})).reason,'CAPTURE_RECEIPT_INVALID');assert.equal(store.calls.includes('insert'),false)}const store=memory();let ticks=0;assert.equal((await run(store,{clock:()=>ticks++?now+60_001:now})).reason,'CAPTURE_RECEIPT_INVALID');assert.equal(store.data.size,0)});
test('source mismatch, historical results and wrong race cannot be resealed',async()=>{for(const change of [r=>r.marketSnapshot.horses[0].odds=99,r=>r.race.historicalResearch=true,r=>r.resultSnapshot={},r=>r.race.raceNo=2]){const store=memory(),r=record();change(r);const before=structuredClone(r);assert.equal((await run(store,{acquire:()=>receipt(r)})).status,'REJECTED');assert.deepEqual(r,before);assert.equal(store.calls.includes('insert'),false)}});
test('two concurrent acquisitions retain the atomic first stored candidate',async()=>{const store=memory(),both=await Promise.all([run(store),run(store,{acquire:()=>receipt(record(99))})]);assert.deepEqual(both.map(x=>x.status).sort(),['CREATED','PRESERVED']);assert.equal(both[0].snapshot.contentSha256,both[1].snapshot.contentSha256);assert.equal(store.data.size,1)});
test('invalid initial clocks, reversed clocks and read errors fail closed',async()=>{const store=memory();assert.equal((await run(store,{clock:()=>NaN,acquire:()=>assert.fail()})).reason,'CAPTURE_CLOCK_INVALID');assert.equal(store.calls.length,0);let ticks=0;assert.equal((await run(store,{clock:()=>ticks++?now-1:now})).reason,'CAPTURE_CLOCK_INVALID');const x=await run({get(){throw Error('private')},insertIfAbsent(){assert.fail()}},{acquire:()=>assert.fail()});assert.equal(x.reason,'STORE_READ_FAILED')});
